In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
#경로 설정 
import os
os.chdir('/content/drive/MyDrive/A2W/데이터')

In [ ]:
import pandas as pd

# 토양도 데이터 불러오기
merge_s_t = pd.read_csv("merge_soil_tree.csv")
merge_s_t = merge_s_t.drop([ "Unnamed: 0" , 'landslide'], axis= 1)
merge_s_t

           umd2  PRRCK_LARG  PRRCK_MDDL  ...  AGCLS_CD  DNST_CD  HEIGHT
0    포항시 남구 연일읍         2.0        26.0  ...         4        C    12.0
1       경주시 양북면         1.0        11.0  ...         3        C    12.0
2    포항시 북구 기계면         2.0        26.0  ...         5        C    14.0
3    포항시 북구 기북면         2.0        26.0  ...         5        C    14.0
4       청송군 부남면         1.0        11.0  ...         1        A     0.0
..          ...         ...         ...  ...       ...      ...     ...
287  포항시 남구 제철동         NaN         NaN  ...         4        C    10.0
288  포항시 남구 장기면         NaN         NaN  ...         5        C    18.0
289     경주시 감포읍         NaN         NaN  ...         4        C    12.0
290     울릉군 울릉읍         NaN         NaN  ...         5        C    16.0
291      울릉군 북면         NaN         NaN  ...         5        C    16.0

[292 rows x 21 columns]

In [ ]:
#경로 설정 
import os
os.chdir('/content/drive/MyDrive/A2W/제출용 코드/preprocessing/soil_preprocessing/data')

In [ ]:
pip install geopandas

Collecting geopandas
  Downloading geopandas-0.9.0-py2.py3-none-any.whl (994 kB)
     |████████████████████████████████| 994 kB 8.6 MB/s
Collecting fiona>=1.8
  Downloading Fiona-1.8.20-cp37-cp37m-manylinux1_x86_64.whl (15.4 MB)
     |████████████████████████████████| 15.4 MB 38 kB/s
Requirement already satisfied: shapely>=1.6 in /usr/local/lib/python3.7/dist-packages (from geopandas) (1.7.1)
Collecting pyproj>=2.2.0
  Downloading pyproj-3.1.0-cp37-cp37m-manylinux2010_x86_64.whl (6.6 MB)
     |████████████████████████████████| 6.6 MB 50.5 MB/s
Requirement already satisfied: pandas>=0.24.0 in /usr/local/lib/python3.7/dist-packages (from geopandas) (1.1.5)
Collecting munch
  Downloading munch-2.5.0-py2.py3-none-any.whl (10 kB)
Requirement already satisfied: certifi in /usr/local/lib/python3.7/dist-packages (from fiona>=1.8->geopandas) (2021.5.30)
Requirement already satisfied: attrs>=17 in /usr/local/lib/python3.7/dist-packages (from fiona>=1.8->geopandas) (21.2.0)
Requirement already satisfied: six>=1.7 in /usr/local/lib/python3.7/dist-packages (from fiona>=1.8->geopandas) (1.15.0)
Requirement already satisfied: click>=4.0 in /usr/local/lib/python3.7/dist-packages (from fiona>=1.8->geopandas) (7.1.2)
Collecting cligj>=0.5
  Downloading cligj-0.7.2-py3-none-any.whl (7.1 kB)
Requirement already satisfied: setuptools in /usr/local/lib/python3.7/dist-packages (from fiona>=1.8->geopandas) (57.2.0)
Collecting click-plugins>=1.0
  Downloading click_plugins-1.1.1-py2.py3-none-any.whl (7.5 kB)
Requirement already satisfied: numpy>=1.15.4 in /usr/local/lib/python3.7/dist-packages (from pandas>=0.24.0->geopandas) (1.19.5)
Requirement already satisfied: python-dateutil>=2.7.3 in /usr/local/lib/python3.7/dist-packages (from pandas>=0.24.0->geopandas) (2.8.1)
Requirement already satisfied: pytz>=2017.2 in /usr/local/lib/python3.7/dist-packages (from pandas>=0.24.0->geopandas) (2018.9)
Installing collected packages: munch, cligj, click-plugins, pyproj, fiona, geopandas
Successfully installed click-plugins-1.1.1 cligj-0.7.2 fiona-1.8.20 geopandas-0.9.0 munch-2.5.0 pyproj-3.1.0

In [ ]:
import geopandas as gpd # GIS 데이터가 있는 데이터 사용을 위한 라이브러리

In [ ]:
# 행정동 경계 파일 읽기
hangjung_gubun = gpd.GeoDataFrame.from_file("umd.shp", encoding = 'utf-8')
# 산사태와 합치기 위한 새로운 변수 umd2(ssg+umd) 생성하기
hangjung_gubun_si = pd.read_csv('umd_si.csv', encoding='utf-8')
hangjung_gubun["sgg"] = hangjung_gubun_si
hangjung_gubun["umd2"] = hangjung_gubun["sgg"] + " " + hangjung_gubun["ADM_DR_NM"]
hangjung_gubun = hangjung_gubun.drop([ "BASE_DATE", "ADM_DR_CD", 'geometry'], axis= 1)
hangjung_gubun.rename(columns={'ADM_DR_NM':'umd'}, inplace=True)
hangjung_gubun

      umd     sgg         umd2
0    구룡포읍  포항시 남구  포항시 남구 구룡포읍
1     연일읍  포항시 남구   포항시 남구 연일읍
2     오천읍  포항시 남구   포항시 남구 오천읍
3     대송면  포항시 남구   포항시 남구 대송면
4     동해면  포항시 남구   포항시 남구 동해면
..    ...     ...          ...
632   쌍백면     합천군      합천군 쌍백면
633   삼가면     합천군      합천군 삼가면
634   가회면     합천군      합천군 가회면
635   대병면     합천군      합천군 대병면
636   용주면     합천군      합천군 용주면

[637 rows x 3 columns]

In [ ]:
# 토양도에 행정동 합치기
merge_s_h_t = pd.merge(merge_s_t, hangjung_gubun, how='inner',on='umd2')
merge_s_h_t

           umd2  PRRCK_LARG  PRRCK_MDDL  ...  HEIGHT  umd     sgg
0    포항시 남구 연일읍         2.0        26.0  ...    12.0  연일읍  포항시 남구
1       경주시 양북면         1.0        11.0  ...    12.0  양북면     경주시
2    포항시 북구 기계면         2.0        26.0  ...    14.0  기계면  포항시 북구
3    포항시 북구 기북면         2.0        26.0  ...    14.0  기북면  포항시 북구
4       청송군 부남면         1.0        11.0  ...     0.0  부남면     청송군
..          ...         ...         ...  ...     ...  ...     ...
287  포항시 남구 제철동         NaN         NaN  ...    10.0  제철동  포항시 남구
288  포항시 남구 장기면         NaN         NaN  ...    18.0  장기면  포항시 남구
289     경주시 감포읍         NaN         NaN  ...    12.0  감포읍     경주시
290     울릉군 울릉읍         NaN         NaN  ...    16.0  울릉읍     울릉군
291      울릉군 북면         NaN         NaN  ...    16.0   북면     울릉군

[292 rows x 23 columns]

In [ ]:
import os
os.chdir('/content/drive/MyDrive/A2W/제출용 코드/merge')

In [ ]:
# 필수 라이브러리

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [ ]:
import os
os.chdir('/content/drive/MyDrive/A2W/제출용 코드/preprocessing/weather_preprocessing')

In [ ]:
# 기상 데이터 불러오기
asos = pd.read_csv('landslide_asos_merged_month.csv')
asos = asos.drop(['sd', 'sgg', 'umd', 'location', 'sum_cnt', 'sum_hpa', 'landslide', 'month'], axis= 1)
asos

       stnId stnNm          tm  avgTa  ...  avgWs  minRhm  avgRhm  n99Rn
0        115   울릉도  2011-06-01   13.6  ...    3.1    81.0    95.5    1.6
1        130    울진  2011-06-01   13.6  ...    1.3    94.0    97.6    NaN
2        136    안동  2011-06-01   16.5  ...    1.1    70.0    88.0   23.5
3        137    상주  2011-06-01   16.1  ...    0.9    77.0    91.9    NaN
4        138    포항  2011-06-01   17.0  ...    1.1    67.0    88.9    2.5
...      ...   ...         ...    ...  ...    ...     ...     ...    ...
42972    285    합천  2019-10-31   11.0  ...    0.7    30.0    72.9    NaN
42973    288    밀양  2019-10-31   11.3  ...    0.5    24.0    72.1    NaN
42974    289    산청  2019-10-31   11.8  ...    1.3    30.0    70.6    NaN
42975    294    거제  2019-10-31   13.9  ...    0.8    29.0    75.0    NaN
42976    295    남해  2019-10-31   14.2  ...    1.0    38.0    67.1    NaN

[42977 rows x 16 columns]

# ASOS데이터에 행정동 데이터 합치기

In [ ]:
# 토양도에서 행정동 데이터 가져오기
dist = merge_s_h_t[['umd', 'sgg', 'umd2']].copy()
dist

     umd     sgg        umd2
0    연일읍  포항시 남구  포항시 남구 연일읍
1    양북면     경주시     경주시 양북면
2    기계면  포항시 북구  포항시 북구 기계면
3    기북면  포항시 북구  포항시 북구 기북면
4    부남면     청송군     청송군 부남면
..   ...     ...         ...
287  제철동  포항시 남구  포항시 남구 제철동
288  장기면  포항시 남구  포항시 남구 장기면
289  감포읍     경주시     경주시 감포읍
290  울릉읍     울릉군     울릉군 울릉읍
291   북면     울릉군      울릉군 북면

[292 rows x 3 columns]

In [ ]:
# sgg의 앞에 2글자 추출하여 loc에 저장
dist['loc'] = dist['sgg'].str[0:2]
dist

     umd     sgg        umd2 loc
0    연일읍  포항시 남구  포항시 남구 연일읍  포항
1    양북면     경주시     경주시 양북면  경주
2    기계면  포항시 북구  포항시 북구 기계면  포항
3    기북면  포항시 북구  포항시 북구 기북면  포항
4    부남면     청송군     청송군 부남면  청송
..   ...     ...         ...  ..
287  제철동  포항시 남구  포항시 남구 제철동  포항
288  장기면  포항시 남구  포항시 남구 장기면  포항
289  감포읍     경주시     경주시 감포읍  경주
290  울릉읍     울릉군     울릉군 울릉읍  울릉
291   북면     울릉군      울릉군 북면  울릉

[292 rows x 4 columns]

In [ ]:
# 특정 지역 loc변수 수정
for i in range(len(dist['loc'])):
  if dist['loc'][i] == '울릉':
    dist['loc'][i] = '울릉도'
  elif dist['loc'][i] == '김해':
    dist['loc'][i] = '김해시'
  elif dist['loc'][i] == '양산':
    dist['loc'][i] = '양산시' 
  elif dist['loc'][i] == '의령':
    dist['loc'][i] = '의령군'
  elif dist['loc'][i] == '함양':
    dist['loc'][i] = '함양군'
  elif dist['loc'][i] == '청송':
    dist['loc'][i] = '청송군'
  elif dist['loc'][i] == '경주':
    dist['loc'][i] = '경주시'
  # 창원의 경우 북창원과 창원 구분이 필요함
  elif dist['loc'][i] == '창원시 마산합포구':
    dist['loc'][i] = '창원'
  elif dist['loc'][i] == '창원시 마산회원구':
    dist['loc'][i] = '북창원'
  elif dist['loc'][i] == '창원시 성산구':
    dist['loc'][i] = '북창원'
  elif dist['loc'][i] == '창원시 진해구':
    dist['loc'][i] = '창원'
  elif dist['loc'][i] == '창원시 의창구':
    dist['loc'][i] = '북창원'

In [ ]:
# ASOS 날씨 데이터 기준 sites
sites = ['115', '130', '136', '137', '138', '143', '152', '155', '159', '253', '255', '257', '263', '264', '271', '272', '273', '162', '192', '276', '277', '278', '279', '281', '283', '284', '285', '288', '289', '294', '295']

sites_index = ['울릉도', '울진', '안동', '상주', '포항', '대구', '울산', '창원', '부산', '김해시', '북창원', '양산시', '의령군', '함양군', '봉화', '영주', '문경', '통영', '진주', '청송군', '영덕', '의성', '구미', '영천', '경주시', '거창', '합천', '밀양', '산청', '거제', '남해']

dic = {key:value for key, value in zip(sites_index, sites)}

dist['stnId'] = 0
missing_area = []

# loc값에 맞는 stnId 매칭
for i in range(len(dist['loc'])):
  if dist['loc'][i] in sites_index:
    dist['stnId'][i] = dic[dist['loc'][i]]
  else:
    missing_area.append(dist['loc'][i])

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  del sys.path[0]

In [ ]:
# 매칭 확인
dist

     umd     sgg        umd2  loc  stnId
0    연일읍  포항시 남구  포항시 남구 연일읍   포항    138
1    양북면     경주시     경주시 양북면  경주시    283
2    기계면  포항시 북구  포항시 북구 기계면   포항    138
3    기북면  포항시 북구  포항시 북구 기북면   포항    138
4    부남면     청송군     청송군 부남면  청송군    276
..   ...     ...         ...  ...    ...
287  제철동  포항시 남구  포항시 남구 제철동   포항    138
288  장기면  포항시 남구  포항시 남구 장기면   포항    138
289  감포읍     경주시     경주시 감포읍  경주시    283
290  울릉읍     울릉군     울릉군 울릉읍  울릉도    115
291   북면     울릉군      울릉군 북면  울릉도    115

[292 rows x 5 columns]

In [ ]:
# 가장 가까운 기상대
closest_area = {'김천': '구미', '예천': '문경', '사천': '진주', '청도': '밀양', '성주': '구미', 
                '고성': '구미', '고령': '합천', '함안': '창원', '하동': '진주', '창녕': '밀양',
                '경산': '영천', '칠곡': '구미', '군위': '의성'}

for i in range(len(dist['loc'])):
  # 영양을 제외한 다른 구역은 가장 가까운 기상대 위치로 날씨 측정
  if dist['loc'][i] in closest_area:
    # closest_area 딕셔너리에 value 값을 key 값 삼아서 그에 해당하는 dic 딕셔너리 sites 코드 value 값 리턴
    curr = closest_area[dist['loc'][i]]
    dist['stnId'][i] = dic[curr]
    # dist['stnId'][i] = dic[closest_area[dist['loc'][i]]
  # 영양의 경우 읍면동 단위에 따라 서로 다른 기상대 위치로 날씨 측정
  if dist['loc'][i] == '영양':
    if dist['umd'][i] == '석보면' or dist['umd'][i] == '영양읍' or dist['umd'][i] == '입암면':
      dist['stnId'][i] = dic['청송군']
    elif dist['umd'][i] == '일월면' or dist['umd'][i] == '수비면':
      dist['stnId'][i] = dic['울진']
    elif dist['umd'][i] == '청기면':
      dist['stnId'][i] = dic['안동']
  if dist['loc'][i] == '창원':
    if dist['sgg'][i] == '창원시 의창구' or dist['sgg'][i] == '창원시 마산회원구' or dist['sgg'][i] == '창원시 성산구':
      dist['stnId'][i] = dic['북창원']

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  # This is added back by InteractiveShellApp.init_path()
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:16: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  app.launch_new_instance()
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:18: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:20: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:23: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [ ]:
# ASOS 데이터와 전처리한 산사태 발생 이력 데이터 결합
# 기준은 tm (날짜), stnId (측정소 ID)

asos_merge = pd.merge(asos, dist, how='outer', on=['stnId'])
asos_merge

        stnId stnNm          tm  avgTa  minTa  ...  n99Rn  umd  sgg     umd2  loc
0         115   울릉도  2011-06-01   13.6   12.7  ...    1.6  울릉읍  울릉군  울릉군 울릉읍  울릉도
1         115   울릉도  2011-06-01   13.6   12.7  ...    1.6   북면  울릉군   울릉군 북면  울릉도
2         115   울릉도  2011-06-02   13.4   11.8  ...    NaN  울릉읍  울릉군  울릉군 울릉읍  울릉도
3         115   울릉도  2011-06-02   13.4   11.8  ...    NaN   북면  울릉군   울릉군 북면  울릉도
4         115   울릉도  2011-06-03   14.6   12.0  ...    NaN  울릉읍  울릉군  울릉군 울릉읍  울릉도
...       ...   ...         ...    ...    ...  ...    ...  ...  ...      ...  ...
412238    295    남해  2019-10-31   14.2    8.2  ...    NaN  설천면  남해군  남해군 설천면   남해
412239    295    남해  2019-10-31   14.2    8.2  ...    NaN  남해읍  남해군  남해군 남해읍   남해
412240    295    남해  2019-10-31   14.2    8.2  ...    NaN   서면  남해군   남해군 서면   남해
412241    295    남해  2019-10-31   14.2    8.2  ...    NaN  이동면  남해군  남해군 이동면   남해
412242    295    남해  2019-10-31   14.2    8.2  ...    NaN  삼동면  남해군  남해군 삼동면   남해

[412243 rows x 20 columns]

In [ ]:
# umd2 기준으로 토양도와 임상도와 날씨 데이터 병합
merge_s_h_a = pd.merge(asos_merge, merge_s_t, how='inner',on='umd2')
merge_s_h_a

        stnId stnNm          tm  avgTa  ...  DMCLS_CD  AGCLS_CD  DNST_CD  HEIGHT
0         115   울릉도  2011-06-01   13.6  ...         1         5        C    16.0
1         115   울릉도  2011-06-02   13.4  ...         1         5        C    16.0
2         115   울릉도  2011-06-03   14.6  ...         1         5        C    16.0
3         115   울릉도  2011-06-04   20.7  ...         1         5        C    16.0
4         115   울릉도  2011-06-05   21.0  ...         1         5        C    16.0
...       ...   ...         ...    ...  ...       ...       ...      ...     ...
408107    295    남해  2019-10-27   12.1  ...         1         3        C    10.0
408108    295    남해  2019-10-28   13.4  ...         1         3        C    10.0
408109    295    남해  2019-10-29   15.4  ...         1         3        C    10.0
408110    295    남해  2019-10-30   13.3  ...         1         3        C    10.0
408111    295    남해  2019-10-31   14.2  ...         1         3        C    10.0

[408112 rows x 40 columns]

In [ ]:
#경로 설정 
import os
os.chdir('/content/drive/MyDrive/A2W/데이터/final')

In [ ]:
# 병합한 데이터를 merge_s_h_a.csv 라는 이름으로 저장

# 불필요한 변수 제거
merge_s_h_a = merge_s_h_a.drop(["umd", 'sgg', 'loc', 'DNST_CD'], axis=1)
merge_s_h_a.to_csv("merge_s_h_a.csv", index=False)

In [ ]:
# 날짜형 데이터
merge_s_h_a["tm"] = pd.to_datetime(merge_s_h_a["tm"])

In [ ]:
#경로 설정 
import os
os.chdir('/content/drive/MyDrive/A2W/데이터')

In [ ]:
# 새로운 산사태 발생 이력 데이터프레임 생성

# 산사태 발생 이력 데이터 불러오기
landslide_CNT = pd.read_csv('landslide_history.csv', encoding='cp949')

# 산사태 발생 이력에 시와 읍면동 기준으로 umd2 생성
landslide_CNT["umd2"] = landslide_CNT["sgg"] + " " + landslide_CNT["umd"]

# 날짜형 데이터
landslide_CNT["date"] = landslide_CNT["date"].astype("str")
landslide_CNT["date"] = pd.to_datetime(landslide_CNT["date"])
landslide_CNT = landslide_CNT.drop(["sd", 'umd', "sgg", "sum_cnt", "sum_hpa"], axis=1)
landslide_CNT.rename(columns={'date':'tm'}, inplace=True)
landslide_CNT["landslide"] = 1

landslide_CNT

            tm        umd2  landslide
0   2011-07-09     밀양시 내일동          1
1   2011-07-09     밀양시 단장면          1
2   2011-07-09     밀양시 무안면          1
3   2011-07-09     밀양시 부북면          1
4   2011-07-09     밀양시 산외면          1
..         ...         ...        ...
354 2019-10-03  포항시 북구 장량동          1
355 2019-10-03  포항시 북구 중앙동          1
356 2019-10-03  포항시 북구 청하면          1
357 2019-10-03  포항시 북구 환여동          1
358 2019-10-03  포항시 북구 흥해읍          1

[359 rows x 3 columns]

In [ ]:
# 날씨, 임상도, 토양도가 합쳐진 데이터와 산사태 발생 이력 데이터 병합 (umd2와 날짜 기준)

merge_final = pd.merge(merge_s_h_a, landslide_CNT, how='inner',on=['tm','umd2'])
merge_final

      stnId stnNm         tm  avgTa  ...  DMCLS_CD  AGCLS_CD  HEIGHT  landslide
0       115   울릉도 2016-10-05   16.9  ...         1         5    16.0          1
1       115   울릉도 2019-10-03   20.3  ...         1         5    16.0          1
2       130    울진 2019-10-03   22.1  ...         1         3    14.0          1
3       130    울진 2019-10-03   22.1  ...         1         3    14.0          1
4       130    울진 2019-10-03   22.1  ...         1         3    14.0          1
...     ...   ...        ...    ...  ...       ...       ...     ...        ...
3950    295    남해 2012-09-17   21.1  ...         1         3    10.0          1
3951    295    남해 2012-09-17   21.1  ...         1         3    10.0          1
3952    295    남해 2012-09-17   21.1  ...         1         3    10.0          1
3953    295    남해 2012-09-17   21.1  ...         1         3    10.0          1
3954    295    남해 2012-09-17   21.1  ...         1         3    10.0          1

[3955 rows x 37 columns]

In [ ]:
# 중복 제거
merge_final.drop_duplicates()

      stnId stnNm         tm  avgTa  ...  DMCLS_CD  AGCLS_CD  HEIGHT  landslide
0       115   울릉도 2016-10-05   16.9  ...         1         5    16.0          1
1       115   울릉도 2019-10-03   20.3  ...         1         5    16.0          1
2       130    울진 2019-10-03   22.1  ...         1         3    14.0          1
14      130    울진 2019-10-03   22.1  ...         0         1     0.0          1
26      130    울진 2019-10-03   22.1  ...         1         4     8.0          1
...     ...   ...        ...    ...  ...       ...       ...     ...        ...
3925    295    남해 2012-09-17   21.1  ...         2         5    12.0          1
3932    295    남해 2012-09-17   21.1  ...         2         5    12.0          1
3939    295    남해 2012-09-17   21.1  ...         2         4     8.0          1
3946    295    남해 2016-10-05   21.6  ...         2         4     8.0          1
3948    295    남해 2012-09-17   21.1  ...         1         3    10.0          1

[359 rows x 37 columns]

In [ ]:
# 산사태가 발생하지 않은 날짜는 0으로 처리

merge_final_real = merge_final
merge_final_real["landslide"] = merge_final["landslide"].fillna(0)
merge_final_real.isnull().sum()

stnId              0
stnNm              0
tm                 0
avgTa            496
minTa             70
maxTa            107
mi10MaxRn     237463
hr1MaxRn      237408
sumRnDur      375415
sumRn         236721
maxInsWs          97
maxWs             97
avgWs            192
minRhm           139
avgRhm           717
n99Rn         382000
umd2            4131
PRRCK_LARG     11068
PRRCK_MDDL     11068
LOCTN_ALTT     11068
LOCTN_GRDN     11068
EIGHT_AGL      11068
CLZN_CD        11068
TPGRP_TPCD     11068
PRDN_FOM_C     11068
SLANT_TYP      11068
SLDPT_TPCD     11068
SCSTX_CD       11068
SLTP_CD        11068
STORUNST        4131
FROR_CD         4131
FRTP_CD         4131
KOFTR_GROU      4131
DMCLS_CD        4131
AGCLS_CD        4131
HEIGHT          5509
landslide          0
dtype: int64

In [ ]:
# umd에 없는 지역 확인하기
merge_final_real[merge_final_real['stnNm'].isin(['대구', '울산', '부산'])]

       stnId stnNm         tm  avgTa  ...  DMCLS_CD  AGCLS_CD  HEIGHT  landslide
48670    143    대구 2011-06-01   19.3  ...       NaN       NaN     NaN        0.0
48671    152    울산 2011-06-01   18.7  ...       NaN       NaN     NaN        0.0
48672    159    부산 2011-06-01   18.7  ...       NaN       NaN     NaN        0.0
48673    143    대구 2011-06-02   20.1  ...       NaN       NaN     NaN        0.0
48674    152    울산 2011-06-02   16.9  ...       NaN       NaN     NaN        0.0
...      ...   ...        ...    ...  ...       ...       ...     ...        ...
52796    152    울산 2019-10-30   13.6  ...       NaN       NaN     NaN        0.0
52797    159    부산 2019-10-30   14.6  ...       NaN       NaN     NaN        0.0
52798    143    대구 2019-10-31   14.1  ...       NaN       NaN     NaN        0.0
52799    152    울산 2019-10-31   15.7  ...       NaN       NaN     NaN        0.0
52800    159    부산 2019-10-31   16.2  ...       NaN       NaN     NaN        0.0

[4131 rows x 37 columns]

In [ ]:
# umd에 없는 지역 제거하기
mergr_del_null = merge_final_real.dropna(subset=['umd2'])
mergr_del_null

        stnId stnNm         tm  avgTa  ...  DMCLS_CD  AGCLS_CD  HEIGHT  landslide
0         115   울릉도 2011-06-01   13.6  ...       1.0       5.0    16.0        0.0
1         115   울릉도 2011-06-02   13.4  ...       1.0       5.0    16.0        0.0
2         115   울릉도 2011-06-03   14.6  ...       1.0       5.0    16.0        0.0
3         115   울릉도 2011-06-04   20.7  ...       1.0       5.0    16.0        0.0
4         115   울릉도 2011-06-05   21.0  ...       1.0       5.0    16.0        0.0
...       ...   ...        ...    ...  ...       ...       ...     ...        ...
412238    295    남해 2019-10-27   12.1  ...       1.0       3.0    10.0        0.0
412239    295    남해 2019-10-28   13.4  ...       1.0       3.0    10.0        0.0
412240    295    남해 2019-10-29   15.4  ...       1.0       3.0    10.0        0.0
412241    295    남해 2019-10-30   13.3  ...       1.0       3.0    10.0        0.0
412242    295    남해 2019-10-31   14.2  ...       1.0       3.0    10.0        0.0

[408112 rows x 37 columns]

In [ ]:
# umd에 없는 지역 제거 확인1
mergr_del_null[mergr_del_null['stnNm'].isin(['대구', '울산', '부산'])]

Empty DataFrame
Columns: [stnId, stnNm, tm, avgTa, minTa, maxTa, mi10MaxRn, hr1MaxRn, sumRnDur, sumRn, maxInsWs, maxWs, avgWs, minRhm, avgRhm, n99Rn, umd2, PRRCK_LARG, PRRCK_MDDL, LOCTN_ALTT, LOCTN_GRDN, EIGHT_AGL, CLZN_CD, TPGRP_TPCD, PRDN_FOM_C, SLANT_TYP, SLDPT_TPCD, SCSTX_CD, SLTP_CD, STORUNST, FROR_CD, FRTP_CD, KOFTR_GROU, DMCLS_CD, AGCLS_CD, HEIGHT, landslide]
Index: []

In [ ]:
# umd에 없는 지역 제거 확인2
mergr_del_null.isnull().sum()

stnId              0
stnNm              0
tm                 0
avgTa            494
minTa             70
maxTa            106
mi10MaxRn     235000
hr1MaxRn      234945
sumRnDur      372877
sumRn         234258
maxInsWs          96
maxWs             96
avgWs            190
minRhm           138
avgRhm           716
n99Rn         378415
umd2               0
PRRCK_LARG      6937
PRRCK_MDDL      6937
LOCTN_ALTT      6937
LOCTN_GRDN      6937
EIGHT_AGL       6937
CLZN_CD         6937
TPGRP_TPCD      6937
PRDN_FOM_C      6937
SLANT_TYP       6937
SLDPT_TPCD      6937
SCSTX_CD        6937
SLTP_CD         6937
STORUNST           0
FROR_CD            0
FRTP_CD            0
KOFTR_GROU         0
DMCLS_CD           0
AGCLS_CD           0
HEIGHT          1378
landslide          0
dtype: int64

In [ ]:
# 중복 제거
sum_all = mergr_del_null.drop_duplicates()

In [ ]:
#경로 설정 
import os
os.chdir('/content/drive/MyDrive/A2W/데이터/final')

In [ ]:
# 날씨, 임상도, 토양도, 산사태 발생 이력이 병합된 최종 데이터를 merge_final_real.csv 라는 이름으로 저장

mergr_del_null.to_csv("merge_final_real.csv", index=False, encoding='utf-8-sig')

In [ ]:
# 날씨, 임상도, 토양도, 산사태 발생 이력이 병합된 최종 데이터를 merge_final_real.csv 라는 이름으로 저장

sum_all.to_csv("sum_all_real.csv", index=False, encoding='utf-8-sig')

In [ ]:
sum_all

        stnId stnNm         tm  avgTa  ...  DMCLS_CD  AGCLS_CD  HEIGHT  landslide
0         115   울릉도 2011-06-01   13.6  ...       1.0       5.0    16.0        0.0
1         115   울릉도 2011-06-02   13.4  ...       1.0       5.0    16.0        0.0
2         115   울릉도 2011-06-03   14.6  ...       1.0       5.0    16.0        0.0
3         115   울릉도 2011-06-04   20.7  ...       1.0       5.0    16.0        0.0
4         115   울릉도 2011-06-05   21.0  ...       1.0       5.0    16.0        0.0
...       ...   ...        ...    ...  ...       ...       ...     ...        ...
412238    295    남해 2019-10-27   12.1  ...       1.0       3.0    10.0        0.0
412239    295    남해 2019-10-28   13.4  ...       1.0       3.0    10.0        0.0
412240    295    남해 2019-10-29   15.4  ...       1.0       3.0    10.0        0.0
412241    295    남해 2019-10-30   13.3  ...       1.0       3.0    10.0        0.0
412242    295    남해 2019-10-31   14.2  ...       1.0       3.0    10.0        0.0

[402072 rows x 37 columns]

In [ ]:
# 1일 후 예측과 2일 후 예측의 초기값은 0으로 설정
sum_all['1day_yn'] = 0.0
sum_all['2day_yn'] = 0.0

# 열을 밀어서 1일 후, 2일 후의 산사태 발생 여부를 표시
# 맨 첫날, 마지막 날의 경우 산사태가 발생하지 않음
sum_all['1day_yn'][1:-1] = sum_all['landslide'][0:-2]
sum_all['2day_yn'][2:-1] = sum_all['landslide'][0:-3]

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  This is separate from the ipykernel package so we can avoid doing imports until
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  import sys
/usr/local/lib/python3.7/dist-packages/pandas/core/series.py:1027: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._set_with(key, value)
/usr/local/lib/python3.7/dist-packages/IPython/core/interactiveshell.py:2882: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  exec(code_obj, self.user_global_ns, self.user_ns)
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [ ]:
# 날씨, 임상도, 토양도, 산사태 발생 이력이 병합된 최종 데이터를 merge_final_real.csv 라는 이름으로 저장

sum_all.to_csv("sum_all_realfinal.csv", index=False, encoding='utf-8-sig')

# **Test data 처리**

In [ ]:
#경로 설정 
import os
os.chdir('/content/drive/MyDrive/A2W/데이터')

In [ ]:
df_test = pd.read_csv("210039_한글.csv")
df_test

            date    sd     sgg umd_x  ... KOFTR_GROU  DMCLS_CD AGCLS_CD  HEIGHT
0     2020-06-10  경상남도     사천시   곤명면  ...       11.0       2.0      4.0    14.0
1     2020-06-11  경상남도     사천시   곤명면  ...       11.0       2.0      4.0    14.0
2     2020-06-12  경상남도     사천시   곤명면  ...       11.0       2.0      4.0    14.0
3     2020-06-10  경상남도     사천시   곤양면  ...       11.0       2.0      4.0    16.0
4     2020-06-11  경상남도     사천시   곤양면  ...       11.0       2.0      4.0    16.0
...          ...   ...     ...   ...  ...        ...       ...      ...     ...
3405  2020-09-06  경상북도  포항시 북구   환여동  ...       15.0       2.0      4.0    12.0
3406  2020-09-03  경상북도  포항시 북구   흥해읍  ...       44.0       1.0      2.0    10.0
3407  2020-09-04  경상북도  포항시 북구   흥해읍  ...       44.0       1.0      2.0    10.0
3408  2020-09-05  경상북도  포항시 북구   흥해읍  ...       44.0       1.0      2.0    10.0
3409  2020-09-06  경상북도  포항시 북구   흥해읍  ...       44.0       1.0      2.0    10.0

[3410 rows x 45 columns]

In [ ]:
df_test.columns

Index(['date', 'sd', 'sgg', 'umd_x', '1day', '1day_yn', '2day', '2day_yn',
       'tm', 'stnId', 'stnNm', 'umd_y', 'umd2', 'avgTa', 'minTa', 'maxTa',
       'mi10MaxRn', 'hr1MaxRn', 'sumRnDur', 'sumRn', 'maxInsWs', 'maxWs',
       'avgWs', 'minRhm', 'avgRhm', 'n99Rn', 'PRRCK_LARG', 'PRRCK_MDDL',
       'LOCTN_ALTT', 'LOCTN_GRDN', 'EIGHT_AGL', 'CLZN_CD', 'TPGRP_TPCD',
       'PRDN_FOM_C', 'SLANT_TYP', 'SLDPT_TPCD', 'SCSTX_CD', 'SLTP_CD',
       'STORUNST', 'FROR_CD', 'FRTP_CD', 'KOFTR_GROU', 'DMCLS_CD', 'AGCLS_CD',
       'HEIGHT'],
      dtype='object')

In [ ]:
df_test_del = df_test.drop(['PRRCK_LARG', 'PRRCK_MDDL',
                            'LOCTN_ALTT', 'LOCTN_GRDN', 'EIGHT_AGL', 'CLZN_CD', 'TPGRP_TPCD',
                            'PRDN_FOM_C', 'SLANT_TYP', 'SLDPT_TPCD', 'SCSTX_CD', 'SLTP_CD',
                            'STORUNST', 'FROR_CD', 'FRTP_CD', 'KOFTR_GROU', 'DMCLS_CD', 'AGCLS_CD',
                            'HEIGHT'], axis=1)

In [ ]:
df_test_del

            date    sd     sgg umd_x  ... avgWs  minRhm avgRhm  n99Rn
0     2020-06-10  경상남도     사천시   곤명면  ...   0.9    48.0   75.8    3.6
1     2020-06-11  경상남도     사천시   곤명면  ...   0.8    62.0   85.9    0.0
2     2020-06-12  경상남도     사천시   곤명면  ...   0.9    67.0   87.5   48.7
3     2020-06-10  경상남도     사천시   곤양면  ...   0.9    48.0   75.8    3.6
4     2020-06-11  경상남도     사천시   곤양면  ...   0.8    62.0   85.9    0.0
...          ...   ...     ...   ...  ...   ...     ...    ...    ...
3405  2020-09-06  경상북도  포항시 북구   환여동  ...   5.0    75.0   85.8   94.0
3406  2020-09-03  경상북도  포항시 북구   흥해읍  ...   6.2    41.0   64.0    0.0
3407  2020-09-04  경상북도  포항시 북구   흥해읍  ...   2.4    36.0   58.6    0.0
3408  2020-09-05  경상북도  포항시 북구   흥해읍  ...   1.3    72.0   86.1   21.6
3409  2020-09-06  경상북도  포항시 북구   흥해읍  ...   5.0    75.0   85.8   94.0

[3410 rows x 26 columns]

In [ ]:
sum_all.columns

Index(['stnId', 'stnNm', 'tm', 'avgTa', 'minTa', 'maxTa', 'mi10MaxRn',
       'hr1MaxRn', 'sumRnDur', 'sumRn', 'maxInsWs', 'maxWs', 'avgWs', 'minRhm',
       'avgRhm', 'n99Rn', 'umd2', 'PRRCK_LARG', 'PRRCK_MDDL', 'LOCTN_ALTT',
       'LOCTN_GRDN', 'EIGHT_AGL', 'CLZN_CD', 'TPGRP_TPCD', 'PRDN_FOM_C',
       'SLANT_TYP', 'SLDPT_TPCD', 'SCSTX_CD', 'SLTP_CD', 'STORUNST', 'FROR_CD',
       'FRTP_CD', 'KOFTR_GROU', 'DMCLS_CD', 'AGCLS_CD', 'HEIGHT', 'landslide',
       '1day_yn', '2day_yn'],
      dtype='object')

In [ ]:
sum_all_del = sum_all.drop(['stnId', 'stnNm', 'tm', 'avgTa', 'minTa', 'maxTa', 'mi10MaxRn',
                            'hr1MaxRn', 'sumRnDur', 'sumRn', 'maxInsWs', 'maxWs', 'avgWs', 'minRhm',
                            'avgRhm', 'n99Rn', 'landslide', '1day_yn', '2day_yn'], axis=1)

In [ ]:
sum_all_del

           umd2  PRRCK_LARG  PRRCK_MDDL  ...  DMCLS_CD  AGCLS_CD  HEIGHT
0       울릉군 울릉읍         NaN         NaN  ...       1.0       5.0    16.0
1       울릉군 울릉읍         NaN         NaN  ...       1.0       5.0    16.0
2       울릉군 울릉읍         NaN         NaN  ...       1.0       5.0    16.0
3       울릉군 울릉읍         NaN         NaN  ...       1.0       5.0    16.0
4       울릉군 울릉읍         NaN         NaN  ...       1.0       5.0    16.0
...         ...         ...         ...  ...       ...       ...     ...
412238  남해군 삼동면         1.0        11.0  ...       1.0       3.0    10.0
412239  남해군 삼동면         1.0        11.0  ...       1.0       3.0    10.0
412240  남해군 삼동면         1.0        11.0  ...       1.0       3.0    10.0
412241  남해군 삼동면         1.0        11.0  ...       1.0       3.0    10.0
412242  남해군 삼동면         1.0        11.0  ...       1.0       3.0    10.0

[402072 rows x 20 columns]

In [ ]:
merge_s_t

           umd2  PRRCK_LARG  PRRCK_MDDL  ...  AGCLS_CD  DNST_CD  HEIGHT
0    포항시 남구 연일읍         2.0        26.0  ...         4        C    12.0
1       경주시 양북면         1.0        11.0  ...         3        C    12.0
2    포항시 북구 기계면         2.0        26.0  ...         5        C    14.0
3    포항시 북구 기북면         2.0        26.0  ...         5        C    14.0
4       청송군 부남면         1.0        11.0  ...         1        A     0.0
..          ...         ...         ...  ...       ...      ...     ...
287  포항시 남구 제철동         NaN         NaN  ...         4        C    10.0
288  포항시 남구 장기면         NaN         NaN  ...         5        C    18.0
289     경주시 감포읍         NaN         NaN  ...         4        C    12.0
290     울릉군 울릉읍         NaN         NaN  ...         5        C    16.0
291      울릉군 북면         NaN         NaN  ...         5        C    16.0

[292 rows x 21 columns]

In [ ]:
df_test_final = pd.merge(df_test_del, merge_s_t, how='inner',on='umd2')
df_test_final

            date    sd  sgg umd_x  ... DMCLS_CD  AGCLS_CD DNST_CD  HEIGHT
0     2020-06-10  경상남도  사천시   곤명면  ...        1         4       C    10.0
1     2020-06-11  경상남도  사천시   곤명면  ...        1         4       C    10.0
2     2020-06-12  경상남도  사천시   곤명면  ...        1         4       C    10.0
3     2020-07-10  경상남도  사천시   곤명면  ...        1         4       C    10.0
4     2020-07-11  경상남도  사천시   곤명면  ...        1         4       C    10.0
...          ...   ...  ...   ...  ...      ...       ...     ...     ...
3405  2020-08-09  경상북도  칠곡군   석적읍  ...        2         5       C    14.0
3406  2020-09-03  경상북도  칠곡군   석적읍  ...        2         5       C    14.0
3407  2020-09-04  경상북도  칠곡군   석적읍  ...        2         5       C    14.0
3408  2020-09-05  경상북도  칠곡군   석적읍  ...        2         5       C    14.0
3409  2020-09-06  경상북도  칠곡군   석적읍  ...        2         5       C    14.0

[3410 rows x 46 columns]

In [ ]:
df_test_final = df_test_final.drop(['DNST_CD'], axis=1)
df_test_final

            date    sd  sgg umd_x  ... KOFTR_GROU  DMCLS_CD AGCLS_CD  HEIGHT
0     2020-06-10  경상남도  사천시   곤명면  ...         11         1        4    10.0
1     2020-06-11  경상남도  사천시   곤명면  ...         11         1        4    10.0
2     2020-06-12  경상남도  사천시   곤명면  ...         11         1        4    10.0
3     2020-07-10  경상남도  사천시   곤명면  ...         11         1        4    10.0
4     2020-07-11  경상남도  사천시   곤명면  ...         11         1        4    10.0
...          ...   ...  ...   ...  ...        ...       ...      ...     ...
3405  2020-08-09  경상북도  칠곡군   석적읍  ...         34         2        5    14.0
3406  2020-09-03  경상북도  칠곡군   석적읍  ...         34         2        5    14.0
3407  2020-09-04  경상북도  칠곡군   석적읍  ...         34         2        5    14.0
3408  2020-09-05  경상북도  칠곡군   석적읍  ...         34         2        5    14.0
3409  2020-09-06  경상북도  칠곡군   석적읍  ...         34         2        5    14.0

[3410 rows x 45 columns]

In [ ]:
#경로 설정 
import os
os.chdir('/content/drive/MyDrive/A2W/데이터/final')

In [ ]:
# 날씨, 임상도, 토양도, 산사태 발생 이력이 병합된 최종 데이터를 merge_final_real.csv 라는 이름으로 저장

df_test_final.to_csv("test_final.csv", index=False, encoding='utf-8-sig')