<a href="https://colab.research.google.com/github/wonkwonlee/a2w-kma-big-data-contest/blob/main/XGBoost_undersample_submission_1v30.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [2]:
#경로 설정 
import os
os.chdir('/content/drive/MyDrive/A2W/데이터/final')

In [3]:
import tensorflow as tf
from tensorflow import keras

import os
import tempfile

import matplotlib as mpl
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import seaborn as sns

import sklearn
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import confusion_matrix
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.metrics import make_scorer, accuracy_score, precision_score, recall_score, f1_score, roc_auc_score
from sklearn.linear_model import LogisticRegression



from xgboost import plot_importance
from xgboost import XGBClassifier

삭제해야할 변수
수종그룹코드(KOFTR_TROUP_CD)
-	81,82,83, 91, 92, 93, 94, 95, 96, 99
-

# 데이터 처리 및 탐색

In [4]:
# Train 데이터셋
raw_df = pd.read_csv("sum_all_realfinal.csv", encoding='utf-8-sig')
#raw_df = pd.read_csv("merge_final_real1.csv", encoding='utf-8-sig')

# Test 검증 데이터셋
test_input = pd.read_csv('test_final.csv', encoding = 'utf-8-sig')
#불필요한 칼럼제거
X_test = test_input.drop(['1day_yn','2day_yn','date','sd','sgg','umd_x','1day','2day','tm','stnId','stnNm','umd_y','umd2'], axis =1)

In [ ]:
raw_df

In [ ]:
raw_df['PRRCK_LARG'].value_counts()

2.0    162475
1.0    154223
3.0     78489
Name: PRRCK_LARG, dtype: int64

In [ ]:
clean_df = raw_df.replace(to_replace = np.nan, value = 0)

In [ ]:
clean_df = raw_df.fillna(0)

In [7]:
raw_df1 = raw_df[['stnId', 'stnNm', 'tm', 'avgTa', 'minTa', 'maxTa', 'mi10MaxRn',
       'hr1MaxRn', 'sumRnDur', 'sumRn', 'maxInsWs', 'maxWs', 'avgWs', 'minRhm',
       'avgRhm', 'n99Rn', 'umd2']]
raw_df2 = raw_df[['PRRCK_LARG', 'PRRCK_MDDL', 'LOCTN_ALTT',
       'LOCTN_GRDN', 'EIGHT_AGL', 'CLZN_CD', 'TPGRP_TPCD', 'PRDN_FOM_C',
       'SLANT_TYP', 'SLDPT_TPCD', 'SCSTX_CD', 'SLTP_CD', 'STORUNST', 'FROR_CD',
       'FRTP_CD', 'KOFTR_GROU', 'DMCLS_CD', 'AGCLS_CD', 'HEIGHT', 'landslide',
       '1day_yn', '2day_yn']]

In [10]:
raw_df2 = raw_df2.fillna(0)

In [ ]:
clean_df.columns

Index(['stnId', 'stnNm', 'tm', 'avgTa', 'minTa', 'maxTa', 'mi10MaxRn',
       'hr1MaxRn', 'sumRnDur', 'sumRn', 'maxInsWs', 'maxWs', 'avgWs', 'minRhm',
       'avgRhm', 'n99Rn', 'umd2', 'PRRCK_LARG', 'PRRCK_MDDL', 'LOCTN_ALTT',
       'LOCTN_GRDN', 'EIGHT_AGL', 'CLZN_CD', 'TPGRP_TPCD', 'PRDN_FOM_C',
       'SLANT_TYP', 'SLDPT_TPCD', 'SCSTX_CD', 'SLTP_CD', 'STORUNST', 'FROR_CD',
       'FRTP_CD', 'KOFTR_GROU', 'DMCLS_CD', 'AGCLS_CD', 'HEIGHT', 'landslide',
       '1day_yn', '2day_yn'],
      dtype='object')

In [ ]:
clean_df.info()

NameError: ignored

In [ ]:
clean_df = clean_df.astype({'PRRCK_LARG': 'object', 'PRRCK_MDDL': 'object', 'CLZN_CD': 'object', 'TPGRP_TPCD': 'object', 'PRDN_FOM_C': 'object',
       'SLANT_TYP': 'object', 'SLDPT_TPCD': 'object', 'SCSTX_CD': 'object', 'SLTP_CD': 'object', 'STORUNST': 'object', 'FROR_CD': 'object',
       'FRTP_CD': 'object', 'KOFTR_GROU': 'object', 'DMCLS_CD': 'object', 'AGCLS_CD': 'object', 'HEIGHT': 'object'})

In [14]:
clean_df = pd.concat([raw_df1, raw_df2], axis=1)
clean_df

        stnId stnNm          tm  avgTa  ...  HEIGHT  landslide  1day_yn  2day_yn
0         115   울릉도  2011-06-01   13.6  ...    16.0        0.0      0.0      0.0
1         115   울릉도  2011-06-02   13.4  ...    16.0        0.0      0.0      0.0
2         115   울릉도  2011-06-03   14.6  ...    16.0        0.0      0.0      0.0
3         115   울릉도  2011-06-04   20.7  ...    16.0        0.0      0.0      0.0
4         115   울릉도  2011-06-05   21.0  ...    16.0        0.0      0.0      0.0
...       ...   ...         ...    ...  ...     ...        ...      ...      ...
402067    295    남해  2019-10-27   12.1  ...    10.0        0.0      0.0      0.0
402068    295    남해  2019-10-28   13.4  ...    10.0        0.0      0.0      0.0
402069    295    남해  2019-10-29   15.4  ...    10.0        0.0      0.0      0.0
402070    295    남해  2019-10-30   13.3  ...    10.0        0.0      0.0      0.0
402071    295    남해  2019-10-31   14.2  ...    10.0        0.0      0.0      0.0

[402072 rows x 39 columns]

In [15]:
clean_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 402072 entries, 0 to 402071
Data columns (total 39 columns):
 #   Column      Non-Null Count   Dtype
---  ------      --------------   -----
 0   stnId       402072 non-null  int64
 1   stnNm       402072 non-null  object
 2   tm          402072 non-null  object
 3   avgTa       401578 non-null  float64
 4   minTa       402002 non-null  float64
 5   maxTa       401966 non-null  float64
 6   mi10MaxRn   167072 non-null  float64
 7   hr1MaxRn    167127 non-null  float64
 8   sumRnDur    33601 non-null   float64
 9   sumRn       167814 non-null  float64
 10  maxInsWs    401976 non-null  float64
 11  maxWs       401976 non-null  float64
 12  avgWs       401882 non-null  float64
 13  minRhm      401934 non-null  float64
 14  avgRhm      401356 non-null  float64
 15  n99Rn       28552 non-null   float64
 16  umd2        402072 non-null  object
 17  PRRCK_LARG  402072 non-null  float64
 18  PRRCK_MDDL  402072 non-null  float64
 19  LOCTN_ALTT  402072 non-null  float64
 20  LOCTN_GRDN  402072 non-null  float64
 21  EIGHT_AGL   402072 non-null  float64
 22  CLZN_CD     402072 non-null  float64
 23  TPGRP_TPCD  402072 non-null  float64
 24  PRDN_FOM_C  402072 non-null  float64
 25  SLANT_TYP   402072 non-null  float64
 26  SLDPT_TPCD  402072 non-null  float64
 27  SCSTX_CD    402072 non-null  float64
 28  SLTP_CD     402072 non-null  float64
 29  STORUNST    402072 non-null  float64
 30  FROR_CD     402072 non-null  float64
 31  FRTP_CD     402072 non-null  float64
 32  KOFTR_GROU  402072 non-null  float64
 33  DMCLS_CD    402072 non-null  float64
 34  AGCLS_CD    402072 non-null  float64
 35  HEIGHT      402072 non-null  float64
 36  landslide   402072 non-null  float64
 37  1day_yn     402072 non-null  float64
 38  2day_yn     402072 non-null  float64
dtypes: float64(35), int64(1), object(3)
memory usage: 119.6+ MB

In [ ]:
pd.options.display.float_format = '{:.5f}'.format
clean_df.describe()

             stnId        avgTa  ...      1day_yn      2day_yn
count 402072.00000 402072.00000  ... 402072.00000 402072.00000
mean     245.19762     21.83967  ...      0.00089      0.00089
std       55.49525      4.91446  ...      0.02987      0.02987
min      115.00000      0.00000  ...      0.00000      0.00000
25%      192.00000     19.00000  ...      0.00000      0.00000
50%      277.00000     22.40000  ...      0.00000      0.00000
75%      284.00000     25.40000  ...      0.00000      0.00000
max      295.00000     34.10000  ...      1.00000      1.00000

[8 rows x 36 columns]

In [ ]:
# if adjust_ratio: # pulsar 데이터 증폭 flow
#     data = np.zeros([2 * star_cnt, 9])
#     data[0:star_cnt,:] = np.asarray(stars, dtype = 'float32')

#     for n in range(star_cnt):
#         data[star_cnt + n] = np.asarray(pulsars[n % pulsar_cnt], dtype = 'float32')

# else:
#     data = np.zeros([star_cnt + pulsar_cnt, 9])
#     data[0:star_cnt,:] = np.asarray(stars, dtype = 'float32')
#     data[star_cnt:,:] = np.asarray(pulsars, dtype = 'float32')

# 이상치 탐지

In [ ]:
#특정 행들만 추출
#columns = X_test.columns.tolist()
#columns.append("landslide")
#columns1 = columns.copy()
#day = ['1day_yn','2day_yn']
#columns1.extend(day)
#df = clean_df[columns]
#columns1
#df_all = clean_df[columns1]

In [ ]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.ensemble import IsolationForest
%matplotlib inline

model=IsolationForest(n_estimators=100, max_samples='auto', n_jobs=-1,
                      max_features=2, contamination=0.01)
model.fit(data_df_scaled.to_numpy())

NameError: ignored

In [ ]:
score = model.decision_function(data_df_scaled.to_numpy())
anomaly = model.predict(data_df_scaled.to_numpy())
data_df_scaled['scores']= score
data_df_scaled['anomaly']= anomaly
anomaly_data = data_df_scaled.loc[data_df_scaled['anomaly']==-1] # 이상값은 -1으로 나타낸다.
anomaly_data

           avgTa    minTa    maxTa  ...  HEIGHT_24.0   scores  anomaly
0       -1.31880 -0.93325 -1.78721  ...     -0.03965 -0.00590       -1
1       -1.39159 -0.91370 -1.87018  ...     -0.03965 -0.00491       -1
2       -1.43318 -0.96258 -1.92204  ...     -0.03965 -0.00153       -1
5       -1.64114 -1.15808 -1.95315  ...     -0.03965 -0.00562       -1
8       -1.55796 -1.23628 -1.77684  ...     -0.03965 -0.00415       -1
...          ...      ...      ...  ...          ...      ...      ...
1830757  0.74003  1.07066  0.36999  ...     -0.03965 -0.00021       -1
1913242  1.47830  1.53987  1.15820  ...     -0.03965 -0.00019       -1
1913648  0.83361  0.92404  0.53593  ...     -0.03965 -0.00085       -1
1915858  0.74003  0.85561  0.48408  ...     -0.03965 -0.00007       -1
1916209  0.57366  0.89471  0.04849  ...     -0.03965 -0.00029       -1

[20938 rows x 145 columns]

In [ ]:
#label_df.info()
data_df_scaled.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2093790 entries, 0 to 2093789
Columns: 145 entries, avgTa to anomaly
dtypes: float64(144), int64(1)
memory usage: 2.3 GB

In [ ]:
scaled_df_all = pd.concat([data_df_scaled,label_df],axis=1)
scaled_df_all

           avgTa    minTa    maxTa  ...  landslide  1day_yn  2day_yn
0       -1.31880 -0.93325 -1.78721  ...    0.00000  0.00000  0.00000
1       -1.39159 -0.91370 -1.87018  ...    0.00000  0.00000  0.00000
2       -1.43318 -0.96258 -1.92204  ...    0.00000  0.00000  0.00000
3       -1.22522 -0.78662 -1.60053  ...    0.00000  0.00000  0.00000
4       -1.27721 -0.94303 -1.73536  ...    0.00000  0.00000  0.00000
...          ...      ...      ...  ...        ...      ...      ...
2093785 -1.05885 -1.01145 -1.23754  ...    0.00000  0.00000  0.00000
2093786 -1.17323 -1.01145 -1.16494  ...    0.00000  0.00000  0.00000
2093787 -1.06925 -0.87460 -1.40348  ...    0.00000  0.00000  0.00000
2093788 -0.69491 -0.47382 -0.69824  ...    0.00000  0.00000  0.00000
2093789 -1.46438 -1.28516 -1.64202  ...    0.00000  0.00000  0.00000

[2093790 rows x 148 columns]

In [ ]:
clean_all = scaled_df_all.drop(anomaly_data.index)
clean_all.head()

     avgTa    minTa    maxTa  mi10MaxRn  ...  anomaly  landslide  1day_yn  2day_yn
3 -1.22522 -0.78662 -1.60053   -0.23632  ...        1    0.00000  0.00000  0.00000
4 -1.27721 -0.94303 -1.73536   -0.23632  ...        1    0.00000  0.00000  0.00000
6 -1.44358 -1.08965 -1.70424   -0.23632  ...        1    0.00000  0.00000  0.00000
7 -1.15243 -0.81595 -1.44496   -0.23632  ...        1    0.00000  0.00000  0.00000
9 -1.57875 -1.20696 -1.87018   -0.23632  ...        1    0.00000  0.00000  0.00000

[5 rows x 148 columns]

In [ ]:
clean_all.drop(['scores','anomaly'],axis=1)

           avgTa    minTa    maxTa  ...  landslide  1day_yn  2day_yn
3       -1.22522 -0.78662 -1.60053  ...    0.00000  0.00000  0.00000
4       -1.27721 -0.94303 -1.73536  ...    0.00000  0.00000  0.00000
6       -1.44358 -1.08965 -1.70424  ...    0.00000  0.00000  0.00000
7       -1.15243 -0.81595 -1.44496  ...    0.00000  0.00000  0.00000
9       -1.57875 -1.20696 -1.87018  ...    0.00000  0.00000  0.00000
...          ...      ...      ...  ...        ...      ...      ...
2093785 -1.05885 -1.01145 -1.23754  ...    0.00000  0.00000  0.00000
2093786 -1.17323 -1.01145 -1.16494  ...    0.00000  0.00000  0.00000
2093787 -1.06925 -0.87460 -1.40348  ...    0.00000  0.00000  0.00000
2093788 -0.69491 -0.47382 -0.69824  ...    0.00000  0.00000  0.00000
2093789 -1.46438 -1.28516 -1.64202  ...    0.00000  0.00000  0.00000

[2072852 rows x 146 columns]

# 1일 후 예측

#### 변수 선택

In [ ]:
clean_df.head()

   stnId stnNm          tm    avgTa  ...   HEIGHT  landslide  1day_yn  2day_yn
0    115   울릉도  2011-06-01 13.60000  ... 16.00000    0.00000  0.00000  0.00000
1    115   울릉도  2011-06-02 13.40000  ... 16.00000    0.00000  0.00000  0.00000
2    115   울릉도  2011-06-03 14.60000  ... 16.00000    0.00000  0.00000  0.00000
3    115   울릉도  2011-06-04 20.70000  ... 16.00000    0.00000  0.00000  0.00000
4    115   울릉도  2011-06-05 21.00000  ... 16.00000    0.00000  0.00000  0.00000

[5 rows x 39 columns]

In [ ]:
#xgboostd의 feature importance를 통해 선정된 변수
columns_select_day1= ['avgRhm', 'maxTa','minTa','maxInsWs','LOCTN_ALTT','maxWs','avgTa','LOCTN_GRDN','avgWs','minRhm','sumRn','mi10MaxRn','hr1MaxRn','sumRnDur','CLZN_CD_4.0','HEIGHT_14.0','AGCLS_CD_5.0','PRRCK_MDDL_22.0','n99Rn','AGCLS_CD_4.0','PRRCK_MDDL_11.0','KOFTR_GROU_34.0','EIGHT_AGL_dir_S','HEIGHT_8.0','EIGHT_AGL_dir_N','KOFTR_GROU_30.0']

In [16]:
#xgboostd의 feature importance를 통해 선정된 변수
columns_select_day1= ['avgTa', 'minTa', 'maxTa', 'mi10MaxRn',
       'hr1MaxRn', 'sumRnDur', 'sumRn', 'maxInsWs', 'maxWs', 'avgWs', 'minRhm',
       'avgRhm', 'n99Rn', 'PRRCK_LARG', 'PRRCK_MDDL', 'LOCTN_ALTT',
       'LOCTN_GRDN', 'EIGHT_AGL', 'CLZN_CD', 'TPGRP_TPCD', 'PRDN_FOM_C',
       'SLANT_TYP', 'SLDPT_TPCD', 'SCSTX_CD', 'SLTP_CD', 'STORUNST', 'FROR_CD',
       'FRTP_CD', 'KOFTR_GROU', 'DMCLS_CD', 'AGCLS_CD', 'HEIGHT']

In [17]:
clean_df.columns

Index(['stnId', 'stnNm', 'tm', 'avgTa', 'minTa', 'maxTa', 'mi10MaxRn',
       'hr1MaxRn', 'sumRnDur', 'sumRn', 'maxInsWs', 'maxWs', 'avgWs', 'minRhm',
       'avgRhm', 'n99Rn', 'umd2', 'PRRCK_LARG', 'PRRCK_MDDL', 'LOCTN_ALTT',
       'LOCTN_GRDN', 'EIGHT_AGL', 'CLZN_CD', 'TPGRP_TPCD', 'PRDN_FOM_C',
       'SLANT_TYP', 'SLDPT_TPCD', 'SCSTX_CD', 'SLTP_CD', 'STORUNST', 'FROR_CD',
       'FRTP_CD', 'KOFTR_GROU', 'DMCLS_CD', 'AGCLS_CD', 'HEIGHT', 'landslide',
       '1day_yn', '2day_yn'],
      dtype='object')

In [18]:
#y = raw_df['1day_yn']
#X = raw_df[columns_select_day1]

y = clean_df['1day_yn']
X = clean_df[columns_select_day1]
#X = clean_df.drop(['1day_yn','2day_yn','tm','umd2','stnId'], axis =1)

In [19]:
X = pd.DataFrame(X, columns=columns_select_day1)
y = pd.DataFrame(y, columns = ['1day_yn'])
df_1day = pd.concat([X,y],axis=1)
df_1day

        avgTa  minTa  maxTa  mi10MaxRn  ...  DMCLS_CD  AGCLS_CD  HEIGHT  1day_yn
0        13.6   12.7   14.9        0.0  ...       1.0       5.0    16.0      0.0
1        13.4   11.8   16.5        0.0  ...       1.0       5.0    16.0      0.0
2        14.6   12.0   18.7        NaN  ...       1.0       5.0    16.0      0.0
3        20.7   18.2   23.9        NaN  ...       1.0       5.0    16.0      0.0
4        21.0   17.9   23.6        NaN  ...       1.0       5.0    16.0      0.0
...       ...    ...    ...        ...  ...       ...       ...     ...      ...
402067   12.1    8.3   18.0        NaN  ...       1.0       3.0    10.0      0.0
402068   13.4    7.3   19.0        NaN  ...       1.0       3.0    10.0      0.0
402069   15.4   10.7   21.0        NaN  ...       1.0       3.0    10.0      0.0
402070   13.3    9.0   20.0        NaN  ...       1.0       3.0    10.0      0.0
402071   14.2    8.2   22.1        NaN  ...       1.0       3.0    10.0      0.0

[402072 rows x 33 columns]

In [20]:
day0 = df_1day[df_1day['1day_yn'] == 0].shape[0]
day1 = df_1day[df_1day['1day_yn'] == 1].shape[0]

In [21]:
df1_1y = df_1day[df_1day['1day_yn'] == 1].copy()
df1_1y

        avgTa  minTa  maxTa  mi10MaxRn  ...  DMCLS_CD  AGCLS_CD  HEIGHT  1day_yn
892      16.1   14.6   19.1        0.0  ...       1.0       5.0    16.0      1.0
2726     18.3   16.7   20.1        0.0  ...       1.0       5.0    16.0      1.0
4103     20.3   16.6   24.8        NaN  ...       1.0       3.0    14.0      1.0
5480     20.3   16.6   24.8        NaN  ...       0.0       1.0     0.0      1.0
6857     20.3   16.6   24.8        NaN  ...       1.0       4.0     8.0      1.0
...       ...    ...    ...        ...  ...       ...       ...     ...      ...
396826   21.6   19.3   25.9        NaN  ...       2.0       5.0    12.0      1.0
398203   21.6   19.3   25.9        NaN  ...       2.0       5.0    12.0      1.0
399580   21.6   19.3   25.9        NaN  ...       2.0       4.0     8.0      1.0
400210   20.8   17.0   27.3        NaN  ...       2.0       4.0     8.0      1.0
400957   21.6   19.3   25.9        NaN  ...       1.0       3.0    10.0      1.0

[359 rows x 33 columns]

1118

In [22]:
for _ in range(day0//day1):
  df_1day = pd.concat([df_1day,df1_1y],axis=0)
  df_1day

In [23]:
df_1day[df_1day['1day_yn'] == 0].shape

(401713, 33)

In [24]:
df_1day[df_1day['1day_yn'] == 1].shape

(401721, 33)

In [25]:
X_1by1 = df_1day.drop(['1day_yn'],axis=1).reset_index(drop=True)
y_1by1 = df_1day['1day_yn'].reset_index(drop=True)

# SAMPLING

In [ ]:
https://shinminyong.tistory.com/34

# ADASYN(Adaptive Synthetic Sampling)

In [ ]:
from imblearn.combine import ADASYN

X_samp, y_samp = ADASYN(random_state=0).fit_sample(X, y)

ImportError: ignored

In [ ]:
from imblearn.combine import SMOTETomek

X_samp, y_samp = SMOTETomek(random_state=4).fit_sample(X, y)

plt.subplot(121)
classification_result2(X, y)
plt.subplot(122)
model_samp = classification_result2(X_samp, y_samp)

ValueError: ignored

# 오버 샘플링

In [ ]:
X = X.astype({'PRRCK_LARG': 'object', 'PRRCK_MDDL': 'object', 'CLZN_CD': 'object', 'TPGRP_TPCD': 'object', 'PRDN_FOM_C': 'object',
       'SLANT_TYP': 'object', 'SLDPT_TPCD': 'object', 'SCSTX_CD': 'object', 'SLTP_CD': 'object', 'STORUNST': 'object', 'FROR_CD': 'object',
       'FRTP_CD': 'object', 'KOFTR_GROU': 'object', 'DMCLS_CD': 'object', 'AGCLS_CD': 'object', 'HEIGHT': 'object'})

In [ ]:
#SMOTE
from imblearn.over_sampling import SMOTE
smote = SMOTE()
X_train_over, y_train_over = smote.fit_sample(X, y)
X_train_over = pd.DataFrame(X_train_over, columns=columns_select_day1)
y_train_over = pd.DataFrame(y_train_over)

/usr/local/lib/python3.7/dist-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function safe_indexing is deprecated; safe_indexing is deprecated in version 0.22 and will be removed in version 0.24.
  warnings.warn(msg, category=FutureWarning)

In [ ]:
X_train_over

            avgTa      minTa      maxTa  ...  DMCLS_CD  AGCLS_CD     HEIGHT
0       13.600000  12.700000  14.900000  ...   1.00000  5.000000  16.000000
1       13.400000  11.800000  16.500000  ...   1.00000  5.000000  16.000000
2       14.600000  12.000000  18.700000  ...   1.00000  5.000000  16.000000
3       20.700000  18.200000  23.900000  ...   1.00000  5.000000  16.000000
4       21.000000  17.900000  23.600000  ...   1.00000  5.000000  16.000000
...           ...        ...        ...  ...       ...       ...        ...
803421  20.504960  16.819957  24.964968  ...   1.04999  4.000000   8.199961
803422  19.385272  15.463968  26.352445  ...   2.00000  4.098370  10.393479
803423  20.810051  16.677653  26.520663  ...   2.00000  4.111735  11.776530
803424  20.827387  18.196268  25.596474  ...   2.00000  4.275933  12.000000
803425  21.866612  18.475187  25.820671  ...   2.00000  4.762635  15.050538

[803426 rows x 32 columns]

### 언더샘플링

In [ ]:
from imblearn.under_sampling import RandomUnderSampler

# 1: 50 비율
X_samp, y_samp = RandomUnderSampler(random_state=1024, ratio={1: 359, 0: 17950}).fit_sample(X, y)
#X_samp, y_samp = RandomUnderSampler(random_state=1024, ratio={1: 359, 0: 7180}).fit_sample(X, y)
X_samp = pd.DataFrame(X_samp, columns=columns_select_day1)
y_samp = pd.DataFrame(y_samp)

#df_samp = pd.concat([X_df, y_df], axis=1)

/usr/local/lib/python3.7/dist-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function safe_indexing is deprecated; safe_indexing is deprecated in version 0.22 and will be removed in version 0.24.
  warnings.warn(msg, category=FutureWarning)

In [ ]:
X_samp = X_samp.astype('float')
X_samp = X_samp.astype({'PRRCK_LARG': 'object', 'PRRCK_MDDL': 'object', 'CLZN_CD': 'object', 'TPGRP_TPCD': 'object', 'PRDN_FOM_C': 'object',
       'SLANT_TYP': 'object', 'SLDPT_TPCD': 'object', 'SCSTX_CD': 'object', 'SLTP_CD': 'object', 'STORUNST': 'object', 'FROR_CD': 'object',
       'FRTP_CD': 'object', 'KOFTR_GROU': 'object', 'DMCLS_CD': 'object', 'AGCLS_CD': 'object', 'HEIGHT': 'object'})

In [26]:
#사용할 모듈 불러오기
from sklearn.metrics import make_scorer, accuracy_score, precision_score, recall_score, f1_score, roc_auc_score
#metrics 함수 정의
def metrics(y_test, pred):
    accuracy = accuracy_score(y_test, pred)
    precision = precision_score(y_test, pred)
    recall = recall_score(y_test, pred)
    f1 = f1_score(y_test, pred)
    roc_score = roc_auc_score(y_test, pred)
    print('정확도 : {0:.2f}, 정밀도 : {1:.2f}, 재현율 : {2:.2f}'.format(accuracy, precision, recall))
    print('f1-score : {0:.2f}, auc : {1:.2f}'.format(f1, roc_score))

### Train, test 분리

In [27]:
# 1:1 ratio
X_train_1, X_test_1, y_train_1, y_test_1 = train_test_split(X_1by1, y_1by1, test_size=0.25, shuffle=True, stratify=y_1by1, random_state=1024)

#normal case
# X_train_1, X_test_1, y_train_1, y_test_1 = train_test_split(X, y, test_size=0.25, shuffle=True, stratify=y, random_state=1024)

# under sampling 분리
# 훈련 데이터와 테스트 데이터를 0.75:0.25의 비율로 분할
# X_train_1, X_test_1, y_train_1, y_test_1 = train_test_split(X_samp, y_samp, test_size=0.25, shuffle=True, stratify=y_samp, random_state=0)

#over sampliung 분리
# X_train_1, X_test_1, y_train_1, y_test_1 = train_test_split(X_train_over, y_train_over, test_size=0.25, shuffle=True, stratify=y_train_over, random_state=0)

print('X_train shape:', X_train_1.shape)
print('X_test shape:', X_test_1.shape)
print('y_train shape:', y_train_1.shape)
print('y_test shape:', y_test_1.shape)

X_train shape: (602575, 32)
X_test shape: (200859, 32)
y_train shape: (602575,)
y_test shape: (200859,)

# CATBOOST

In [28]:
pip install catboost

Collecting catboost
  Downloading catboost-0.26.1-cp37-none-manylinux1_x86_64.whl (67.4 MB)
     |████████████████████████████████| 67.4 MB 29 kB/s
Requirement already satisfied: scipy in /usr/local/lib/python3.7/dist-packages (from catboost) (1.4.1)
Requirement already satisfied: pandas>=0.24.0 in /usr/local/lib/python3.7/dist-packages (from catboost) (1.1.5)
Requirement already satisfied: graphviz in /usr/local/lib/python3.7/dist-packages (from catboost) (0.10.1)
Requirement already satisfied: numpy>=1.16.0 in /usr/local/lib/python3.7/dist-packages (from catboost) (1.19.5)
Requirement already satisfied: matplotlib in /usr/local/lib/python3.7/dist-packages (from catboost) (3.2.2)
Requirement already satisfied: plotly in /usr/local/lib/python3.7/dist-packages (from catboost) (4.4.1)
Requirement already satisfied: six in /usr/local/lib/python3.7/dist-packages (from catboost) (1.15.0)
Requirement already satisfied: python-dateutil>=2.7.3 in /usr/local/lib/python3.7/dist-packages (from pandas>=0.24.0->catboost) (2.8.1)
Requirement already satisfied: pytz>=2017.2 in /usr/local/lib/python3.7/dist-packages (from pandas>=0.24.0->catboost) (2018.9)
Requirement already satisfied: kiwisolver>=1.0.1 in /usr/local/lib/python3.7/dist-packages (from matplotlib->catboost) (1.3.1)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.7/dist-packages (from matplotlib->catboost) (0.10.0)
Requirement already satisfied: pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.1 in /usr/local/lib/python3.7/dist-packages (from matplotlib->catboost) (2.4.7)
Requirement already satisfied: retrying>=1.3.3 in /usr/local/lib/python3.7/dist-packages (from plotly->catboost) (1.3.3)
Installing collected packages: catboost
Successfully installed catboost-0.26.1

In [29]:
X_train_1 = X_train_1.astype({'PRRCK_LARG': 'int', 'PRRCK_MDDL': 'int', 'CLZN_CD': 'int', 'TPGRP_TPCD': 'int', 'PRDN_FOM_C': 'int',
       'SLANT_TYP': 'int', 'SLDPT_TPCD': 'int', 'SCSTX_CD': 'int', 'SLTP_CD': 'int', 'STORUNST': 'int', 'FROR_CD': 'int',
       'FRTP_CD': 'int', 'KOFTR_GROU': 'int', 'DMCLS_CD': 'int', 'AGCLS_CD': 'int', 'HEIGHT': 'int'})

In [30]:
X_train_1 = X_train_1.astype({'PRRCK_LARG': 'object', 'PRRCK_MDDL': 'object', 'CLZN_CD': 'object', 'TPGRP_TPCD': 'object', 'PRDN_FOM_C': 'object',
       'SLANT_TYP': 'object', 'SLDPT_TPCD': 'object', 'SCSTX_CD': 'object', 'SLTP_CD': 'object', 'STORUNST': 'object', 'FROR_CD': 'object',
       'FRTP_CD': 'object', 'KOFTR_GROU': 'object', 'DMCLS_CD': 'object', 'AGCLS_CD': 'object', 'HEIGHT': 'object'})

In [31]:
X_test_1 = X_test_1.astype({'PRRCK_LARG': 'int', 'PRRCK_MDDL': 'int', 'CLZN_CD': 'int', 'TPGRP_TPCD': 'int', 'PRDN_FOM_C': 'int',
       'SLANT_TYP': 'int', 'SLDPT_TPCD': 'int', 'SCSTX_CD': 'int', 'SLTP_CD': 'int', 'STORUNST': 'int', 'FROR_CD': 'int',
       'FRTP_CD': 'int', 'KOFTR_GROU': 'int', 'DMCLS_CD': 'int', 'AGCLS_CD': 'int', 'HEIGHT': 'int'})

In [32]:
X_test_1 = X_test_1.astype({'PRRCK_LARG': 'object', 'PRRCK_MDDL': 'object', 'CLZN_CD': 'object', 'TPGRP_TPCD': 'object', 'PRDN_FOM_C': 'object',
       'SLANT_TYP': 'object', 'SLDPT_TPCD': 'object', 'SCSTX_CD': 'object', 'SLTP_CD': 'object', 'STORUNST': 'object', 'FROR_CD': 'object',
       'FRTP_CD': 'object', 'KOFTR_GROU': 'object', 'DMCLS_CD': 'object', 'AGCLS_CD': 'object', 'HEIGHT': 'object'})

In [ ]:
X_train_1

        avgTa  minTa  maxTa  mi10MaxRn  ...  KOFTR_GROU  DMCLS_CD  AGCLS_CD  HEIGHT
729989   20.0   17.2   24.6        0.0  ...          32         1         4      12
613783   20.9   16.1   28.3        0.0  ...          11         2         4      12
157600   20.1   16.3   23.8        0.0  ...          32         1         4      12
97378    28.8   25.2   34.6        0.0  ...          11         2         5      12
32900    21.9   17.2   29.7        2.0  ...          15         1         3      12
...       ...    ...    ...        ...  ...         ...       ...       ...     ...
646685   21.9   17.5   28.8        0.0  ...          11         2         4      16
727116   23.0   21.5   26.5        5.0  ...          32         1         4      12
30816    26.7   24.6   28.7        2.0  ...          15         1         3      12
661272   20.3   16.6   24.8        0.0  ...          12         1         3      14
232886   24.7   21.0   29.1        0.0  ...          11         2         5      12

[602575 rows x 32 columns]

In [ ]:
X_train_1.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 13731 entries, 16778 to 6717
Data columns (total 32 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   avgTa       13731 non-null  float64
 1   minTa       13731 non-null  float64
 2   maxTa       13731 non-null  float64
 3   mi10MaxRn   13731 non-null  float64
 4   hr1MaxRn    13731 non-null  float64
 5   sumRnDur    13731 non-null  float64
 6   sumRn       13731 non-null  float64
 7   maxInsWs    13731 non-null  float64
 8   maxWs       13731 non-null  float64
 9   avgWs       13731 non-null  float64
 10  minRhm      13731 non-null  float64
 11  avgRhm      13731 non-null  float64
 12  n99Rn       13731 non-null  float64
 13  PRRCK_LARG  13731 non-null  object
 14  PRRCK_MDDL  13731 non-null  object
 15  LOCTN_ALTT  13731 non-null  float64
 16  LOCTN_GRDN  13731 non-null  float64
 17  EIGHT_AGL   13731 non-null  float64
 18  CLZN_CD     13731 non-null  object
 19  TPGRP_TPCD  13731 non-null  object
 20  PRDN_FOM_C  13731 non-null  object
 21  SLANT_TYP   13731 non-null  object
 22  SLDPT_TPCD  13731 non-null  object
 23  SCSTX_CD    13731 non-null  object
 24  SLTP_CD     13731 non-null  object
 25  STORUNST    13731 non-null  object
 26  FROR_CD     13731 non-null  object
 27  FRTP_CD     13731 non-null  object
 28  KOFTR_GROU  13731 non-null  object
 29  DMCLS_CD    13731 non-null  object
 30  AGCLS_CD    13731 non-null  object
 31  HEIGHT      13731 non-null  object
dtypes: float64(16), object(16)
memory usage: 3.5+ MB

In [ ]:
cat_features = np.where(X_train_1.dtypes.astype("str").isin(["category","object"]))[0]
cat_features

array([13, 14, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31])

In [60]:
from catboost import CatBoostClassifier

# cat_features = np.where(X_train_1.dtypes.astype("str").isin(["category","object"]))[0]
cat_features = [13, 14, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31]
# cat_features = ['PRRCK_LARG', 'PRRCK_MDDL', 'CLZN_CD', 'TPGRP_TPCD', 'PRDN_FOM_C',
#        'SLANT_TYP', 'SLDPT_TPCD', 'SCSTX_CD', 'SLTP_CD', 'STORUNST', 'FROR_CD',
#        'FRTP_CD', 'KOFTR_GROU', 'DMCLS_CD', 'AGCLS_CD', 'HEIGHT']

model = CatBoostClassifier(learning_rate= iterations=20)

cat1 = model.fit(X_train_1, y_train_1, eval_set=(X_test_1, y_test_1),
            early_stopping_rounds=20, cat_features=cat_features)
pred_cat1 = model.predict(X_test_1)
metrics(y_test_1, pred_cat1)

Learning rate set to 0.5
0:	learn: 0.4034324	test: 0.4038963	best: 0.4038963 (0)	total: 81ms	remaining: 1.54s
1:	learn: 0.2633016	test: 0.2639457	best: 0.2639457 (1)	total: 147ms	remaining: 1.33s
2:	learn: 0.1841145	test: 0.1840665	best: 0.1840665 (2)	total: 212ms	remaining: 1.2s
3:	learn: 0.1496164	test: 0.1498595	best: 0.1498595 (3)	total: 303ms	remaining: 1.21s
4:	learn: 0.1247119	test: 0.1246774	best: 0.1246774 (4)	total: 367ms	remaining: 1.1s
5:	learn: 0.1052111	test: 0.1046250	best: 0.1046250 (5)	total: 428ms	remaining: 998ms
6:	learn: 0.0927528	test: 0.0919086	best: 0.0919086 (6)	total: 492ms	remaining: 914ms
7:	learn: 0.0771973	test: 0.0761322	best: 0.0761322 (7)	total: 570ms	remaining: 856ms
8:	learn: 0.0691847	test: 0.0681426	best: 0.0681426 (8)	total: 630ms	remaining: 770ms
9:	learn: 0.0598298	test: 0.0587263	best: 0.0587263 (9)	total: 697ms	remaining: 697ms
10:	learn: 0.0564035	test: 0.0552934	best: 0.0552934 (10)	total: 763ms	remaining: 624ms
11:	learn: 0.0503966	test: 0.0495237	best: 0.0495237 (11)	total: 829ms	remaining: 553ms
12:	learn: 0.0418119	test: 0.0406852	best: 0.0406852 (12)	total: 895ms	remaining: 482ms
13:	learn: 0.0357240	test: 0.0346860	best: 0.0346860 (13)	total: 964ms	remaining: 413ms
14:	learn: 0.0326396	test: 0.0317350	best: 0.0317350 (14)	total: 1.03s	remaining: 344ms
15:	learn: 0.0306457	test: 0.0297505	best: 0.0297505 (15)	total: 1.1s	remaining: 274ms
16:	learn: 0.0285388	test: 0.0277023	best: 0.0277023 (16)	total: 1.16s	remaining: 205ms
17:	learn: 0.0267997	test: 0.0259670	best: 0.0259670 (17)	total: 1.23s	remaining: 136ms
18:	learn: 0.0251474	test: 0.0243257	best: 0.0243257 (18)	total: 1.29s	remaining: 68.1ms
19:	learn: 0.0228130	test: 0.0219699	best: 0.0219699 (19)	total: 1.36s	remaining: 0us

bestTest = 0.02196994844
bestIteration = 19

정확도 : 0.99, 정밀도 : 0.99, 재현율 : 1.00
f1-score : 0.99, auc : 0.99

# LightGBM

In [ ]:
from lightgbm import LGBMClassifier, plot_importance

lgb = LGBMClassifier(n_estimaotrs = 400,boost_from_average = False )
evals = [(X_test_1, y_test_1)]
lgb1 = lgb.fit(X_train_1, y_train_1, early_stopping_rounds = 1000, eval_metric = "logloss", eval_set = evals, verbose = True)

In [ ]:
lgb_pred = lgb1.predict(X_test_1)
metrics(y_test_1, lgb_pred)

정확도 : 0.93, 정밀도 : 0.88, 재현율 : 1.00
f1-score : 0.94, auc : 0.93

# scaling - 표준화 작업 
각 특성의 평균을 0, 분산을 1로 스케일링합니다.
즉, 데이터를 정규분포로 만듭니다.
최솟값과 최댓값의 크기를 제한하지 않기 때문에, 어떤 알고리즘에서는 문제가 있을 수 있습니다.
회귀보다 분류에 유용합니다.

In [ ]:
X_train_1.shape

(3140146, 26)

In [ ]:
#clean_df_drop = clean_df.drop(['tm','umd2','landslide','1day_yn','2day_yn'],axis=1)
#column = clean_df_drop.columns.tolist()
pd.set_option('display.max_rows', 500)

scaler = StandardScaler()
# StandardScaler 로 데이터 셋 변환. fit( ) 과 transform( ) 호출.  
scaler.fit(X_train_1)
X_train_1 = scaler.transform(X_train_1)

scaler.fit(X_test_1)
X_test_1 = scaler.transform(X_test_1)
#data_df_scaled = pd.DataFrame(data=data_scaled, columns = columns_select_day1)
#print('feature 들의 평균 값')
#print(data_df_scaled.mean())
#print('\nfeature 들의 분산 값')
#print(data_df_scaled.var())

In [ ]:
X_test_1.shape

(1046716, 26)

# Imbalace-xgboost

 모델을 돌리기전에 데이터 타입을 numpy 등으로 바꿔줘야함 - 샘플링을 하는 경우 자동으로 적용됨(참고)

In [70]:
pip install imbalance-xgboost

Collecting imbalance-xgboost
  Downloading imbalance_xgboost-0.8.1-py3-none-any.whl (15 kB)
Requirement already satisfied: numpy>=1.11 in /usr/local/lib/python3.7/dist-packages (from imbalance-xgboost) (1.19.5)
Collecting xgboost>=1.1.1
  Downloading xgboost-1.4.2-py3-none-manylinux2010_x86_64.whl (166.7 MB)
     |████████████████████████████████| 166.7 MB 3.8 kB/s
Requirement already satisfied: scikit-learn>=0.19 in /usr/local/lib/python3.7/dist-packages (from imbalance-xgboost) (0.22.2.post1)
Requirement already satisfied: joblib>=0.11 in /usr/local/lib/python3.7/dist-packages (from scikit-learn>=0.19->imbalance-xgboost) (1.0.1)
Requirement already satisfied: scipy>=0.17.0 in /usr/local/lib/python3.7/dist-packages (from scikit-learn>=0.19->imbalance-xgboost) (1.4.1)
Installing collected packages: xgboost, imbalance-xgboost
  Attempting uninstall: xgboost
    Found existing installation: xgboost 0.90
    Uninstalling xgboost-0.90:
      Successfully uninstalled xgboost-0.90
Successfully installed imbalance-xgboost-0.8.1 xgboost-1.4.2

In [71]:
from imxgboost.imbalance_xgb import imbalance_xgboost as imb_xgb

#xgboster_weight = imb_xgb(special_objective='weighted')
#CV_weight_booster1 = GridSearchCV(xgboster_weight,  {"imbalance_alpha":[1.5,2.0,2.5,3.0,4.0]})
#CV_weight_booster1 = GridSearchCV(xgboster_weight,  {"imbalance_alpha":[1.5]})
#CV_weight_booster1.fit(X_train_1, y_train_1)
#opt_weight_booster1 = CV_weight_booster1.best_estimator_

#focal method
xgboster_focal = imb_xgb(special_objective='focal')
CV_focal_booster1 = GridSearchCV(xgboster_focal, {"focal_gamma":[1.0]})
CV_focal_booster1.fit(X_train_1, y_train_1)
opt_focal_booster1 = CV_focal_booster1.best_estimator_
#metrics(y_test_1, CV_weight_booster1)

/usr/local/lib/python3.7/dist-packages/sklearn/model_selection/_validation.py:536: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details:
KeyError: "None of [Int64Index([463887, 187597,   2802, 129076,  83816, 275398, 475175, 160219,\n            262109, 101756,\n            ...\n            448359, 183328, 269345, 149295, 286276, 423824, 336474,  99076,\n             71295, 320081],\n           dtype='int64', length=361545)] are in the [columns]"

  FitFailedWarning)
/usr/local/lib/python3.7/dist-packages/sklearn/model_selection/_validation.py:536: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details:
KeyError: "None of [Int64Index([322708, 253697, 460312, 424342, 287624, 239831, 358165, 257410,\n             27634, 409457,\n            ...\n            216563, 135949, 468442, 354861, 112093, 256897, 404386,  37023,\n            363739,  76447],\n           dtype='int64', length=361545)] are in the [columns]"

  FitFailedWarning)
/usr/local/lib/python3.7/dist-packages/sklearn/model_selection/_validation.py:536: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details:
KeyError: "None of [Int64Index([329892, 377959,  48421, 285929, 346067, 408017, 264545, 413103,\n            171758, 396386,\n            ...\n            358519, 263357, 236182,  44260, 303696, 254137, 424427,  36054,\n            357344, 150200],\n           dtype='int64', length=361545)] are in the [columns]"

  FitFailedWarning)
/usr/local/lib/python3.7/dist-packages/sklearn/model_selection/_validation.py:536: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details:
KeyError: "None of [Int64Index([ 27823, 457990,  55579, 429362, 398177,  48988, 345087,  91070,\n             80970, 243897,\n            ...\n             60759,  28812, 131995,  37839, 386571, 268803, 446126, 439472,\n             64983,  48492],\n           dtype='int64', length=361545)] are in the [columns]"

  FitFailedWarning)
/usr/local/lib/python3.7/dist-packages/sklearn/model_selection/_validation.py:536: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details:
KeyError: "None of [Int64Index([168227, 170516, 264995, 243829,  35786, 241817, 100072, 311633,\n             34744, 105549,\n            ...\n            364563, 156971,  60313, 338987, 122147, 242852, 248462, 463439,\n            423064,  19387],\n           dtype='int64', length=361545)] are in the [columns]"

  FitFailedWarning)

KeyError: ignored

In [ ]:
class_output = opt_focal_booster1.predict_determine(X_test_1, y=None)
class_output

array([1., 0., 1., ..., 1., 0., 0.], dtype=float32)

# XGBOOST

In [69]:
xgb = XGBClassifier()

#xgb_param_grid = {
#    'n_estimators' : [100, 200, 400, 600],
#    'learning_rate' : [0.01, 0.05, 0.1, 0.15, 0.2],
#    'max_depth' : [4, 6, 8, 10, 12],
#}
#xgb = XGBClassifier(n_estimators=500, learning_rate = 0.1, max_depth = 4)
#xgb_grid = GridSearchCV(xgb, param_grid = xgb_param_grid, scoring="accuracy", n_jobs= -1, verbose = 1)
evals = [(X_test_1, y_test_1)]
xgb1 =xgb.fit(X_train_1, y_train_1, early_stopping_rounds = 100, eval_metric = "logloss", eval_set = evals, verbose = 1)

ValueError: ignored

In [ ]:
xgb_pred = xgb1.predict(X_test_1)
metrics(y_test_1, xgb_pred)

정확도 : 0.93, 정밀도 : 0.88, 재현율 : 1.00
f1-score : 0.94, auc : 0.93

In [ ]:
fig, ax = plt.subplots(figsize=(50,50))
plt.figure(figsize=(100,80))
plot_importance(xgb, ax=ax)

# 앙상블
#### bagging, bossting, stackin, voting의 방법중에서 voting을 선정함
#### Voting이란 서로 다른 알고리즘을 가진 분류기를 결합하는 방법이다.

In [ ]:
import pickle

# Save Model
with open('./voting_model.pkl', 'wb') as f:
    pickle.dump(voting_clf, f)

# Load Model
with open('./voting_model.pkl', 'rb') as f:
    voting_clf = pickle.load(f)

# 2일 후 예측

In [ ]:
clean_df["2day_yn"].value_counts()

0.00000    401713
1.00000       359
Name: 2day_yn, dtype: int64

In [ ]:
columns_select_day2 = ['avgRhm', 'maxTa','minTa','avgTa','maxInsWs','avgWs','LOCTN_ALTT','LOCTN_GRDN','minRhm','maxWs','sumRn','hr1MaxRn','sumRnDur','n99Rn','mi10MaxRn','PRRCK_LARG_2.0','AGCLS_CD_5.0','HEIGHT_14.0','AGCLS_CD_6.0','KOFTR_GROU_11.0','EIGHT_AGL_dir_N']

In [34]:
#xgboostd의 feature importance를 통해 선정된 변수
columns_select_day2= ['avgTa', 'minTa', 'maxTa', 'mi10MaxRn',
       'hr1MaxRn', 'sumRnDur', 'sumRn', 'maxInsWs', 'maxWs', 'avgWs', 'minRhm',
       'avgRhm', 'n99Rn', 'PRRCK_LARG', 'PRRCK_MDDL', 'LOCTN_ALTT',
       'LOCTN_GRDN', 'EIGHT_AGL', 'CLZN_CD', 'TPGRP_TPCD', 'PRDN_FOM_C',
       'SLANT_TYP', 'SLDPT_TPCD', 'SCSTX_CD', 'SLTP_CD', 'STORUNST', 'FROR_CD',
       'FRTP_CD', 'KOFTR_GROU', 'DMCLS_CD', 'AGCLS_CD', 'HEIGHT']

In [35]:
y_2 = clean_df['2day_yn']
X_2 = clean_df[columns_select_day2]
#X_2 = clean_df.drop(['1day_yn','2day_yn','tm','umd2','stnId'], axis =1)

In [36]:
X = pd.DataFrame(X_2, columns=columns_select_day2)
y = pd.DataFrame(y_2, columns = ['2day_yn'])
df_2day = pd.concat([X,y],axis=1)
df_2day

        avgTa  minTa  maxTa  mi10MaxRn  ...  DMCLS_CD  AGCLS_CD  HEIGHT  2day_yn
0        13.6   12.7   14.9        0.0  ...       1.0       5.0    16.0      0.0
1        13.4   11.8   16.5        0.0  ...       1.0       5.0    16.0      0.0
2        14.6   12.0   18.7        NaN  ...       1.0       5.0    16.0      0.0
3        20.7   18.2   23.9        NaN  ...       1.0       5.0    16.0      0.0
4        21.0   17.9   23.6        NaN  ...       1.0       5.0    16.0      0.0
...       ...    ...    ...        ...  ...       ...       ...     ...      ...
402067   12.1    8.3   18.0        NaN  ...       1.0       3.0    10.0      0.0
402068   13.4    7.3   19.0        NaN  ...       1.0       3.0    10.0      0.0
402069   15.4   10.7   21.0        NaN  ...       1.0       3.0    10.0      0.0
402070   13.3    9.0   20.0        NaN  ...       1.0       3.0    10.0      0.0
402071   14.2    8.2   22.1        NaN  ...       1.0       3.0    10.0      0.0

[402072 rows x 33 columns]

In [37]:
day0 = df_2day[df_2day['2day_yn'] == 0].shape[0]
day1 = df_2day[df_2day['2day_yn'] == 1].shape[0]

In [38]:
df2_2y = df_2day[df_2day['2day_yn'] == 1].copy()
df2_2y

        avgTa  minTa  maxTa  mi10MaxRn  ...  DMCLS_CD  AGCLS_CD  HEIGHT  2day_yn
893      16.9   14.5   19.6        1.0  ...       1.0       5.0    16.0      1.0
2727     15.6   13.4   18.7        4.0  ...       1.0       5.0    16.0      1.0
4104     17.4   13.8   21.5        4.0  ...       1.0       3.0    14.0      1.0
5481     17.4   13.8   21.5        4.0  ...       0.0       1.0     0.0      1.0
6858     17.4   13.8   21.5        4.0  ...       1.0       4.0     8.0      1.0
...       ...    ...    ...        ...  ...       ...       ...     ...      ...
396827   20.8   16.9   25.4        NaN  ...       2.0       5.0    12.0      1.0
398204   20.8   16.9   25.4        NaN  ...       2.0       5.0    12.0      1.0
399581   20.8   16.9   25.4        NaN  ...       2.0       4.0     8.0      1.0
400211   19.8   18.3   22.6        1.0  ...       2.0       4.0     8.0      1.0
400958   20.8   16.9   25.4        NaN  ...       1.0       3.0    10.0      1.0

[359 rows x 33 columns]

1118

In [39]:
for _ in range(day0//day1):
  df_2day = pd.concat([df_2day,df2_2y],axis=0)
  df_2day

In [40]:
df_2day[df_2day['2day_yn'] == 0].shape

(401713, 33)

In [41]:
df_2day[df_2day['2day_yn'] == 1].shape

(401721, 33)

In [42]:
X_2by1 = df_2day.drop(['2day_yn'],axis=1).reset_index(drop=True)
y_2by1 = df_2day['2day_yn'].reset_index(drop=True)

###  오버샘플링

In [ ]:
#SMOTE
from imblearn.over_sampling import SMOTE
smote = SMOTE()
X_train_over_2, y_train_over_2 = smote.fit_sample(X_2, y_2)
X_train_over_2 = pd.DataFrame(X_train_over_2, columns=columns_select_day2)
y_train_over_2 = pd.DataFrame(y_train_over_2)

/usr/local/lib/python3.7/dist-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function safe_indexing is deprecated; safe_indexing is deprecated in version 0.22 and will be removed in version 0.24.
  warnings.warn(msg, category=FutureWarning)

### 언더 샘플링

In [ ]:
from imblearn.under_sampling import RandomUnderSampler

# 1: 50 비율
X_samp_2, y_samp_2 = RandomUnderSampler(random_state=1024, ratio={1: 359, 0: 17950}).fit_sample(X_2, y_2)
#X_samp_2, y_samp_2 = RandomUnderSampler(random_state=1024, ratio={1: 359, 0: 7180}).fit_sample(X_2, y_2)

X_samp_2 = pd.DataFrame(X_samp_2, columns=columns_select_day2)
y_samp_2 = pd.DataFrame(y_samp_2)

#df_samp = pd.concat([X_df, y_df], axis=1)

/usr/local/lib/python3.7/dist-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function safe_indexing is deprecated; safe_indexing is deprecated in version 0.22 and will be removed in version 0.24.
  warnings.warn(msg, category=FutureWarning)

In [ ]:
X_samp_2 = X_samp_2.astype('float')
X_samp_2 = X_samp_2.astype({'PRRCK_LARG': 'object', 'PRRCK_MDDL': 'object', 'CLZN_CD': 'object', 'TPGRP_TPCD': 'object', 'PRDN_FOM_C': 'object',
       'SLANT_TYP': 'object', 'SLDPT_TPCD': 'object', 'SCSTX_CD': 'object', 'SLTP_CD': 'object', 'STORUNST': 'object', 'FROR_CD': 'object',
       'FRTP_CD': 'object', 'KOFTR_GROU': 'object', 'DMCLS_CD': 'object', 'AGCLS_CD': 'object', 'HEIGHT': 'object'})

### Train, test 분리

In [43]:
# 1:1 ratio
X_train_2, X_test_2, y_train_2, y_test_2 = train_test_split(X_2by1, y_2by1, test_size=0.25, shuffle=True, stratify=y_2by1, random_state=1024)

#normal case
# X_train_2, X_test_2, y_train_2, y_test_2 = train_test_split(X_2, y_2, test_size=0.25, shuffle=True, stratify= y_2, random_state=1024)

#undersampling 분리
# X_train_2, X_test_2, y_train_2, y_test_2 = train_test_split(X_samp_2, y_samp_2, test_size=0.25, shuffle=True, stratify=y_samp_2, random_state=0)

#over sampliung 분리
# X_train_2, X_test_2, y_train_2, y_test_2 = train_test_split(X_train_over_2, y_train_over_2, test_size=0.25, shuffle=True, stratify=y_train_over_2, random_state=0)

print('X_train shape:', X_train_2.shape)
print('X_test shape:', X_test_2.shape)
print('y_train shape:', y_train_2.shape)
print('y_test shape:', y_test_2.shape)

X_train shape: (602575, 32)
X_test shape: (200859, 32)
y_train shape: (602575,)
y_test shape: (200859,)

# SVM -시도 중이나 이유를 찾지 못함

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.font_manager
from sklearn import svm

# Generate some abnormal novel observations
X_outliers = np.random.uniform(low=-4, high=4, size=(20, 2))

# fit the model
clf = svm.OneClassSVM(nu=0.1, kernel="rbf", gamma=0.1)
clf.fit(X_train_1)
y_pred_train = clf.predict(X_train_1)
y_pred_test = clf.predict(X_test_1)
y_pred_outliers = clf.predict(X_outliers)

In [ ]:
#clean_df_drop = clean_df.drop(['tm','umd2','landslide','1day_yn','2day_yn'],axis=1)
#column = clean_df_drop.columns.tolist()
pd.set_option('display.max_rows', 500)

scaler = StandardScaler()
# StandardScaler 로 데이터 셋 변환. fit( ) 과 transform( ) 호출.  
scaler.fit(X_train_2)
X_train_2 = scaler.transform(X_train_2)

scaler.fit(X_test_2)
X_test_2 = scaler.transform(X_test_2)

#data_df_scaled = pd.DataFrame(data=data_scaled, columns = columns_select_day1)
#print('feature 들의 평균 값')
#print(data_df_scaled.mean())
#print('\nfeature 들의 분산 값')
#print(data_df_scaled.var())

# CATBOOST

In [ ]:
pip install catboost

Collecting catboost
  Downloading catboost-0.26.1-cp37-none-manylinux1_x86_64.whl (67.4 MB)
     |████████████████████████████████| 67.4 MB 29 kB/s
Requirement already satisfied: six in /usr/local/lib/python3.7/dist-packages (from catboost) (1.15.0)
Requirement already satisfied: graphviz in /usr/local/lib/python3.7/dist-packages (from catboost) (0.10.1)
Requirement already satisfied: matplotlib in /usr/local/lib/python3.7/dist-packages (from catboost) (3.2.2)
Requirement already satisfied: scipy in /usr/local/lib/python3.7/dist-packages (from catboost) (1.4.1)
Requirement already satisfied: pandas>=0.24.0 in /usr/local/lib/python3.7/dist-packages (from catboost) (1.1.5)
Requirement already satisfied: plotly in /usr/local/lib/python3.7/dist-packages (from catboost) (4.4.1)
Requirement already satisfied: numpy>=1.16.0 in /usr/local/lib/python3.7/dist-packages (from catboost) (1.19.5)
Requirement already satisfied: python-dateutil>=2.7.3 in /usr/local/lib/python3.7/dist-packages (from pandas>=0.24.0->catboost) (2.8.1)
Requirement already satisfied: pytz>=2017.2 in /usr/local/lib/python3.7/dist-packages (from pandas>=0.24.0->catboost) (2018.9)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.7/dist-packages (from matplotlib->catboost) (0.10.0)
Requirement already satisfied: pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.1 in /usr/local/lib/python3.7/dist-packages (from matplotlib->catboost) (2.4.7)
Requirement already satisfied: kiwisolver>=1.0.1 in /usr/local/lib/python3.7/dist-packages (from matplotlib->catboost) (1.3.1)
Requirement already satisfied: retrying>=1.3.3 in /usr/local/lib/python3.7/dist-packages (from plotly->catboost) (1.3.3)
Installing collected packages: catboost
Successfully installed catboost-0.26.1

# CATBOOST

In [44]:
X_train_2 = X_train_2.astype({'PRRCK_LARG': 'int', 'PRRCK_MDDL': 'int', 'CLZN_CD': 'int', 'TPGRP_TPCD': 'int', 'PRDN_FOM_C': 'int',
       'SLANT_TYP': 'int', 'SLDPT_TPCD': 'int', 'SCSTX_CD': 'int', 'SLTP_CD': 'int', 'STORUNST': 'int', 'FROR_CD': 'int',
       'FRTP_CD': 'int', 'KOFTR_GROU': 'int', 'DMCLS_CD': 'int', 'AGCLS_CD': 'int', 'HEIGHT': 'int'})
X_train_2 = X_train_2.astype({'PRRCK_LARG': 'object', 'PRRCK_MDDL': 'object', 'CLZN_CD': 'object', 'TPGRP_TPCD': 'object', 'PRDN_FOM_C': 'object',
       'SLANT_TYP': 'object', 'SLDPT_TPCD': 'object', 'SCSTX_CD': 'object', 'SLTP_CD': 'object', 'STORUNST': 'object', 'FROR_CD': 'object',
       'FRTP_CD': 'object', 'KOFTR_GROU': 'object', 'DMCLS_CD': 'object', 'AGCLS_CD': 'object', 'HEIGHT': 'object'})
X_test_2 = X_test_2.astype({'PRRCK_LARG': 'int', 'PRRCK_MDDL': 'int', 'CLZN_CD': 'int', 'TPGRP_TPCD': 'int', 'PRDN_FOM_C': 'int',
       'SLANT_TYP': 'int', 'SLDPT_TPCD': 'int', 'SCSTX_CD': 'int', 'SLTP_CD': 'int', 'STORUNST': 'int', 'FROR_CD': 'int',
       'FRTP_CD': 'int', 'KOFTR_GROU': 'int', 'DMCLS_CD': 'int', 'AGCLS_CD': 'int', 'HEIGHT': 'int'})
X_test_2 = X_test_2.astype({'PRRCK_LARG': 'object', 'PRRCK_MDDL': 'object', 'CLZN_CD': 'object', 'TPGRP_TPCD': 'object', 'PRDN_FOM_C': 'object',
       'SLANT_TYP': 'object', 'SLDPT_TPCD': 'object', 'SCSTX_CD': 'object', 'SLTP_CD': 'object', 'STORUNST': 'object', 'FROR_CD': 'object',
       'FRTP_CD': 'object', 'KOFTR_GROU': 'object', 'DMCLS_CD': 'object', 'AGCLS_CD': 'object', 'HEIGHT': 'object'})

In [ ]:
X_train_2

        avgTa  minTa  maxTa  mi10MaxRn  ...  KOFTR_GROU  DMCLS_CD  AGCLS_CD  HEIGHT
729989   18.2   12.6   24.6        0.0  ...          32         1         4      12
613783   19.9   17.0   26.0        0.0  ...          11         2         4      12
157600   20.1   16.3   23.8        0.0  ...          32         1         4      12
97378    28.8   25.2   34.6        0.0  ...          11         2         5      12
32900    21.9   17.2   29.7        2.0  ...          15         1         3      12
...       ...    ...    ...        ...  ...         ...       ...       ...     ...
646685   22.1   18.4   26.9        0.0  ...          11         2         4      16
727116   24.7   22.1   29.2        3.0  ...          32         1         4      12
30816    26.7   24.6   28.7        2.0  ...          15         1         3      12
661272   17.4   13.8   21.5        4.0  ...          12         1         3      14
232886   24.7   21.0   29.1        0.0  ...          11         2         5      12

[602575 rows x 32 columns]

In [61]:
from catboost import CatBoostClassifier

cat_features = np.where(X_train_2.dtypes.astype("str").isin(["category","object"]))[0]
# cat_features = [13, 14, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31]
# cat_features = ['PRRCK_LARG', 'PRRCK_MDDL', 'CLZN_CD', 'TPGRP_TPCD', 'PRDN_FOM_C',
#        'SLANT_TYP', 'SLDPT_TPCD', 'SCSTX_CD', 'SLTP_CD', 'STORUNST', 'FROR_CD',
#        'FRTP_CD', 'KOFTR_GROU', 'DMCLS_CD', 'AGCLS_CD', 'HEIGHT']

model = CatBoostClassifier(iterations=20)

cat2 = model.fit(X_train_2, y_train_2, eval_set=(X_test_2, y_test_2),
            early_stopping_rounds=20, cat_features=cat_features)
pred_cat2 = model.predict(X_test_2)
metrics(y_test_2,pred_cat2)

Learning rate set to 0.5
0:	learn: 0.4034348	test: 0.4048494	best: 0.4048494 (0)	total: 88.7ms	remaining: 1.69s
1:	learn: 0.3103716	test: 0.3118376	best: 0.3118376 (1)	total: 171ms	remaining: 1.54s
2:	learn: 0.2565527	test: 0.2585600	best: 0.2585600 (2)	total: 249ms	remaining: 1.41s
3:	learn: 0.2257785	test: 0.2270904	best: 0.2270904 (3)	total: 344ms	remaining: 1.38s
4:	learn: 0.1896234	test: 0.1908696	best: 0.1908696 (4)	total: 421ms	remaining: 1.26s
5:	learn: 0.1573767	test: 0.1583359	best: 0.1583359 (5)	total: 493ms	remaining: 1.15s
6:	learn: 0.1236178	test: 0.1241158	best: 0.1241158 (6)	total: 574ms	remaining: 1.07s
7:	learn: 0.1043452	test: 0.1046100	best: 0.1046100 (7)	total: 671ms	remaining: 1.01s
8:	learn: 0.0861362	test: 0.0861881	best: 0.0861881 (8)	total: 744ms	remaining: 909ms
9:	learn: 0.0782424	test: 0.0782399	best: 0.0782399 (9)	total: 825ms	remaining: 825ms
10:	learn: 0.0723534	test: 0.0722994	best: 0.0722994 (10)	total: 904ms	remaining: 739ms
11:	learn: 0.0675420	test: 0.0675520	best: 0.0675520 (11)	total: 988ms	remaining: 658ms
12:	learn: 0.0594351	test: 0.0596464	best: 0.0596464 (12)	total: 1.07s	remaining: 576ms
13:	learn: 0.0527638	test: 0.0528395	best: 0.0528395 (13)	total: 1.14s	remaining: 490ms
14:	learn: 0.0483906	test: 0.0489142	best: 0.0489142 (14)	total: 1.21s	remaining: 404ms
15:	learn: 0.0429809	test: 0.0437903	best: 0.0437903 (15)	total: 1.28s	remaining: 320ms
16:	learn: 0.0378555	test: 0.0385820	best: 0.0385820 (16)	total: 1.35s	remaining: 239ms
17:	learn: 0.0357981	test: 0.0362888	best: 0.0362888 (17)	total: 1.43s	remaining: 159ms
18:	learn: 0.0320931	test: 0.0325521	best: 0.0325521 (18)	total: 1.51s	remaining: 79.3ms
19:	learn: 0.0291671	test: 0.0294302	best: 0.0294302 (19)	total: 1.59s	remaining: 0us

bestTest = 0.02943022215
bestIteration = 19

정확도 : 0.99, 정밀도 : 0.99, 재현율 : 1.00
f1-score : 0.99, auc : 0.99

# LightGBM

In [ ]:
from lightgbm import LGBMClassifier, plot_importance

lgb = LGBMClassifier(n_estimaotrs = 400)
evals = [(X_test_2, y_test_2)]
lgb2 = lgb.fit(X_train_2, y_train_2, early_stopping_rounds = 100, eval_metric = "logloss", eval_set = evals, verbose = True)

In [ ]:
lgb_pred_2 = lgb2.predict(X_test_2)
metrics(y_test_2, lgb_pred_2)

정확도 : 0.91, 정밀도 : 0.85, 재현율 : 0.98
f1-score : 0.92, auc : 0.91

# Imbalace-xgboost

 모델을 돌리기전에 데이터 타입을 numpy 등으로 바꿔줘야함 - 샘플링을 하는 경우 자동으로 적용됨(참고)

In [ ]:
from imxgboost.imbalance_xgb import imbalance_xgboost as imb_xgb

xgboster_weight = imb_xgb(special_objective='weighted')
CV_weight_booster2 = GridSearchCV(xgboster_weight,  {"imbalance_alpha":[1.5]})
#CV_weight_booster2 = GridSearchCV(xgboster_weight,  {"imbalance_alpha":[1.5,2.0,2.5,3.0,4.0]})
CV_weight_booster2.fit(X_train_2, y_train_2)
opt_weight_booster2 = CV_weight_booster2.best_estimator_

#focal method
#xgboster_focal = imb_xgb(special_objective='focal')
#CV_focal_booster2 = GridSearchCV(xgboster_focal, {"focal_gamma":[1.0]})
#CV_focal_booster2.fit(X_train_2, y_train_2)
#opt_focal_booster2 = CV_focal_booster2.best_estimator_

# XGboost

In [ ]:
xgb = XGBClassifier()

#xgb_param_grid = {
#    'n_estimators' : [100, 200, 400, 600],
#    'learning_rate' : [0.01, 0.05, 0.1, 0.15, 0.2],
#    'max_depth' : [4, 6, 8, 10, 12],
#}
#xgb2 = XGBClassifier(n_estimators=500, learning_rate = 0.1, max_depth = 4)
#xgb_grid = GridSearchCV(xgb, param_grid = xgb_param_grid, scoring="accuracy", n_jobs= -1, verbose = 1)
evals = [(X_test_2, y_test_2)]
xgb2 = xgb2.fit(X_train_2, y_train_2, early_stopping_rounds = 100, eval_metric = "logloss", eval_set = evals, verbose = 1)

/usr/local/lib/python3.7/dist-packages/xgboost/sklearn.py:1146: UserWarning: The use of label encoder in XGBClassifier is deprecated and will be removed in a future release. To remove this warning, do the following: 1) Pass option use_label_encoder=False when constructing XGBClassifier object; and 2) Encode your labels (y) as integers starting with 0, i.e. 0, 1, 2, ..., [num_class - 1].
  warnings.warn(label_encoder_deprecation_msg, UserWarning)

[0]	validation_0-logloss:0.63657
[1]	validation_0-logloss:0.58997
[2]	validation_0-logloss:0.55122
[3]	validation_0-logloss:0.51970
[4]	validation_0-logloss:0.48765
[5]	validation_0-logloss:0.46079
[6]	validation_0-logloss:0.43832
[7]	validation_0-logloss:0.41503
[8]	validation_0-logloss:0.39448
[9]	validation_0-logloss:0.37717
[10]	validation_0-logloss:0.35898
[11]	validation_0-logloss:0.34529
[12]	validation_0-logloss:0.33477
[13]	validation_0-logloss:0.32180
[14]	validation_0-logloss:0.30918
[15]	validation_0-logloss:0.30442
[16]	validation_0-logloss:0.30041
[17]	validation_0-logloss:0.29242
[18]	validation_0-logloss:0.28898
[19]	validation_0-logloss:0.28438
[20]	validation_0-logloss:0.27810
[21]	validation_0-logloss:0.27678
[22]	validation_0-logloss:0.27636
[23]	validation_0-logloss:0.27750
[24]	validation_0-logloss:0.27963
[25]	validation_0-logloss:0.27697
[26]	validation_0-logloss:0.27354
[27]	validation_0-logloss:0.27118
[28]	validation_0-logloss:0.27070
[29]	validation_0-logloss:0.27557
[30]	validation_0-logloss:0.28046
[31]	validation_0-logloss:0.27515
[32]	validation_0-logloss:0.27497
[33]	validation_0-logloss:0.28108
[34]	validation_0-logloss:0.27625
[35]	validation_0-logloss:0.27566
[36]	validation_0-logloss:0.28262
[37]	validation_0-logloss:0.29130
[38]	validation_0-logloss:0.28779
[39]	validation_0-logloss:0.28467
[40]	validation_0-logloss:0.29254
[41]	validation_0-logloss:0.29916
[42]	validation_0-logloss:0.29508
[43]	validation_0-logloss:0.30260
[44]	validation_0-logloss:0.30528
[45]	validation_0-logloss:0.31192
[46]	validation_0-logloss:0.31907
[47]	validation_0-logloss:0.31473
[48]	validation_0-logloss:0.32387
[49]	validation_0-logloss:0.32476
[50]	validation_0-logloss:0.32722
[51]	validation_0-logloss:0.33835
[52]	validation_0-logloss:0.35056
[53]	validation_0-logloss:0.34420
[54]	validation_0-logloss:0.34064
[55]	validation_0-logloss:0.34897
[56]	validation_0-logloss:0.36395
[57]	validation_0-logloss:0.36213
[58]	validation_0-logloss:0.37553
[59]	validation_0-logloss:0.37232
[60]	validation_0-logloss:0.38294
[61]	validation_0-logloss:0.39247
[62]	validation_0-logloss:0.40218
[63]	validation_0-logloss:0.41001
[64]	validation_0-logloss:0.42123
[65]	validation_0-logloss:0.41929
[66]	validation_0-logloss:0.41724
[67]	validation_0-logloss:0.42618
[68]	validation_0-logloss:0.43245
[69]	validation_0-logloss:0.44227
[70]	validation_0-logloss:0.44014
[71]	validation_0-logloss:0.45146
[72]	validation_0-logloss:0.45364
[73]	validation_0-logloss:0.45143
[74]	validation_0-logloss:0.46270
[75]	validation_0-logloss:0.47291
[76]	validation_0-logloss:0.48968
[77]	validation_0-logloss:0.48533
[78]	validation_0-logloss:0.48630
[79]	validation_0-logloss:0.49884
[80]	validation_0-logloss:0.51136
[81]	validation_0-logloss:0.50817
[82]	validation_0-logloss:0.50572
[83]	validation_0-logloss:0.50273
[84]	validation_0-logloss:0.51560
[85]	validation_0-logloss:0.52693
[86]	validation_0-logloss:0.53949
[87]	validation_0-logloss:0.55552
[88]	validation_0-logloss:0.56260
[89]	validation_0-logloss:0.55793
[90]	validation_0-logloss:0.57152
[91]	validation_0-logloss:0.56934
[92]	validation_0-logloss:0.56580
[93]	validation_0-logloss:0.57850
[94]	validation_0-logloss:0.58961
[95]	validation_0-logloss:0.58582
[96]	validation_0-logloss:0.59732
[97]	validation_0-logloss:0.61500
[98]	validation_0-logloss:0.61609
[99]	validation_0-logloss:0.63073
[100]	validation_0-logloss:0.62706
[101]	validation_0-logloss:0.62484
[102]	validation_0-logloss:0.62548
[103]	validation_0-logloss:0.62265
[104]	validation_0-logloss:0.63696
[105]	validation_0-logloss:0.64956
[106]	validation_0-logloss:0.66350
[107]	validation_0-logloss:0.66167
[108]	validation_0-logloss:0.67633
[109]	validation_0-logloss:0.67622
[110]	validation_0-logloss:0.67295
[111]	validation_0-logloss:0.67433
[112]	validation_0-logloss:0.66933
[113]	validation_0-logloss:0.66799
[114]	validation_0-logloss:0.66840
[115]	validation_0-logloss:0.68350
[116]	validation_0-logloss:0.69801
[117]	validation_0-logloss:0.71075
[118]	validation_0-logloss:0.72661
[119]	validation_0-logloss:0.72255
[120]	validation_0-logloss:0.73921
[121]	validation_0-logloss:0.73452
[122]	validation_0-logloss:0.74048
[123]	validation_0-logloss:0.75146
[124]	validation_0-logloss:0.76800
[125]	validation_0-logloss:0.76319
[126]	validation_0-logloss:0.77831
[127]	validation_0-logloss:0.77882

In [ ]:
xgb_pred_2 = xgb2.predict(X_test_2)
metrics(y_test_2, xgb_pred_2)

정확도 : 0.88, 정밀도 : 0.81, 재현율 : 1.00
f1-score : 0.89, auc : 0.88

In [ ]:
fig, ax = plt.subplots(figsize=(100,80))
plt.figure(figsize=(100,80))
plot_importance(xgb2, ax=ax)

# Submission 실행

In [46]:
# Test 검증 데이터셋
test_input = pd.read_csv('test_final.csv', encoding = 'utf-8')
#test_input = pd.read_csv('data/210039_한글.csv', encoding = 'utf-8')
#불필요한 칼럼제거
X_test = test_input.drop(['1day_yn','2day_yn','date','sd','sgg','umd_x','1day','2day','tm','stnId','stnNm','umd_y','umd2'], axis =1)
#columns = X_test.columns.tolist()

X_test = X_test.fillna(0)
X_test = X_test.astype({'PRRCK_LARG': 'int', 'PRRCK_MDDL': 'int', 'CLZN_CD': 'int', 'TPGRP_TPCD': 'int', 'PRDN_FOM_C': 'int',
       'SLANT_TYP': 'int', 'SLDPT_TPCD': 'int', 'SCSTX_CD': 'int', 'SLTP_CD': 'int', 'STORUNST': 'int', 'FROR_CD': 'int',
       'FRTP_CD': 'int', 'KOFTR_GROU': 'int', 'DMCLS_CD': 'int', 'AGCLS_CD': 'int', 'HEIGHT': 'int'})
X_test = X_test.astype({'PRRCK_LARG': 'object', 'PRRCK_MDDL': 'object', 'CLZN_CD': 'object', 'TPGRP_TPCD': 'object', 'PRDN_FOM_C': 'object',
       'SLANT_TYP': 'object', 'SLDPT_TPCD': 'object', 'SCSTX_CD': 'object', 'SLTP_CD': 'object', 'STORUNST': 'object', 'FROR_CD': 'object',
       'FRTP_CD': 'object', 'KOFTR_GROU': 'object', 'DMCLS_CD': 'object', 'AGCLS_CD': 'object', 'HEIGHT': 'object'})

#xgboost 결과 중요칼럼 추출 (날짜별)
#1day
columns1 = ['avgTa', 'minTa', 'maxTa', 'mi10MaxRn',
       'hr1MaxRn', 'sumRnDur', 'sumRn', 'maxInsWs', 'maxWs', 'avgWs', 'minRhm',
       'avgRhm', 'n99Rn', 'PRRCK_LARG', 'PRRCK_MDDL', 'LOCTN_ALTT',
       'LOCTN_GRDN', 'EIGHT_AGL', 'CLZN_CD', 'TPGRP_TPCD', 'PRDN_FOM_C',
       'SLANT_TYP', 'SLDPT_TPCD', 'SCSTX_CD', 'SLTP_CD', 'STORUNST', 'FROR_CD',
       'FRTP_CD', 'KOFTR_GROU', 'DMCLS_CD', 'AGCLS_CD', 'HEIGHT'] 
X_test_day1 = X_test[columns_select_day1]

#2day
columns2 =['avgTa', 'minTa', 'maxTa', 'mi10MaxRn',
       'hr1MaxRn', 'sumRnDur', 'sumRn', 'maxInsWs', 'maxWs', 'avgWs', 'minRhm',
       'avgRhm', 'n99Rn', 'PRRCK_LARG', 'PRRCK_MDDL', 'LOCTN_ALTT',
       'LOCTN_GRDN', 'EIGHT_AGL', 'CLZN_CD', 'TPGRP_TPCD', 'PRDN_FOM_C',
       'SLANT_TYP', 'SLDPT_TPCD', 'SCSTX_CD', 'SLTP_CD', 'STORUNST', 'FROR_CD',
       'FRTP_CD', 'KOFTR_GROU', 'DMCLS_CD', 'AGCLS_CD', 'HEIGHT'] 
X_test_day2 = X_test[columns_select_day2]

In [ ]:
X_test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3410 entries, 0 to 3409
Data columns (total 32 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   avgTa       3410 non-null   float64
 1   minTa       3410 non-null   float64
 2   maxTa       3410 non-null   float64
 3   mi10MaxRn   3410 non-null   float64
 4   hr1MaxRn    3410 non-null   float64
 5   sumRnDur    3410 non-null   float64
 6   sumRn       3410 non-null   float64
 7   maxInsWs    3410 non-null   float64
 8   maxWs       3410 non-null   float64
 9   avgWs       3410 non-null   float64
 10  minRhm      3410 non-null   float64
 11  avgRhm      3410 non-null   float64
 12  n99Rn       3410 non-null   float64
 13  PRRCK_LARG  3410 non-null   object
 14  PRRCK_MDDL  3410 non-null   object
 15  LOCTN_ALTT  3410 non-null   float64
 16  LOCTN_GRDN  3410 non-null   float64
 17  EIGHT_AGL   3410 non-null   float64
 18  CLZN_CD     3410 non-null   object
 19  TPGRP_TPCD  3410 non-null   object
 20  PRDN_FOM_C  3410 non-null   object
 21  SLANT_TYP   3410 non-null   object
 22  SLDPT_TPCD  3410 non-null   object
 23  SCSTX_CD    3410 non-null   object
 24  SLTP_CD     3410 non-null   object
 25  STORUNST    3410 non-null   object
 26  FROR_CD     3410 non-null   object
 27  FRTP_CD     3410 non-null   object
 28  KOFTR_GROU  3410 non-null   object
 29  DMCLS_CD    3410 non-null   object
 30  AGCLS_CD    3410 non-null   object
 31  HEIGHT      3410 non-null   object
dtypes: float64(16), object(16)
memory usage: 852.6+ KB

In [ ]:
#clean_df_drop = clean_df.drop(['tm','umd2','landslide','1day_yn','2day_yn'],axis=1)
#column = clean_df_drop.columns.tolist()
pd.set_option('display.max_rows', 500)

scaler = StandardScaler()
# StandardScaler 로 데이터 셋 변환. fit( ) 과 transform( ) 호출.  
scaler.fit(X_test_day1)
X_test_day1 = scaler.transform(X_test_day1)
scaler.fit(X_test_day2)
X_test_day2 = scaler.transform(X_test_day2)
#data_df_scaled = pd.DataFrame(data=data_scaled, columns = columns_select_day1)
#print('feature 들의 평균 값')
#print(data_df_scaled.mean())
#print('\nfeature 들의 분산 값')
#print(data_df_scaled.var())

In [62]:
#catboost
#1day 예측
pred_test_day1 = cat1.predict(X_test_day1)
#2day 예측
pred_test_day2 = cat2.predict(X_test_day2)

In [ ]:
#lgbboost
#1day 예측
pred_test_day1 = lgb1.predict(X_test_day1)
#2day 예측
pred_test_day2 = lgb2.predict(X_test_day2.to_numpy())

ValueError: ignored

In [ ]:
#imxgb
#weight 방법
#1day 예측
pred_test_day1 = opt_weight_booster1.predict_determine(X_test_day1)
#2day 예측
pred_test_day2 = opt_weight_booster2.predict_determine(X_test_day2)

#focal 방법
#1day 예측
#pred_test_day1 = opt_focal_booster1.predict_determine(X_test_day1.to_numpy())
#2day 예측
#pred_test_day2 = opt_focal_booster2.predict_determine(X_test_day2.to_numpy())

NameError: ignored

In [ ]:
pred_test_day1

array([0., 0., 0., ..., 0., 0., 0.])

In [ ]:
#xgboost
#1day 예측
pred_test_day1 = xgb1.predict(X_test_day1)
#2day 예측
pred_test_day2 = xgb2.predict(X_test_day2)

NameError: ignored

In [63]:
#제출 파일 생성
test_input['1day_yn'] = pred_test_day1
test_input['2day_yn'] = pred_test_day2
test_input.head()

         date    sd  sgg umd_x  ... KOFTR_GROU  DMCLS_CD AGCLS_CD  HEIGHT
0  2020-06-10  경상남도  사천시   곤명면  ...         11         1        4    10.0
1  2020-06-11  경상남도  사천시   곤명면  ...         11         1        4    10.0
2  2020-06-12  경상남도  사천시   곤명면  ...         11         1        4    10.0
3  2020-07-10  경상남도  사천시   곤명면  ...         11         1        4    10.0
4  2020-07-11  경상남도  사천시   곤명면  ...         11         1        4    10.0

[5 rows x 45 columns]

In [64]:
test_input["1day_yn"].value_counts()

0.0    3398
1.0      12
Name: 1day_yn, dtype: int64

In [65]:
test_input["2day_yn"].value_counts()

0.0    3388
1.0      22
Name: 2day_yn, dtype: int64

In [ ]:
# 파일 저장
test_input.to_csv("210039_cat1by1null.csv",encoding='euc-kr',index=False)

In [66]:
final = test_input[['date',	'sd',	'sgg',	'umd_x',	'1day',	'1day_yn',	'2day',	'2day_yn']]

In [67]:
final = final.rename(columns={'umd_x':'umd'})

In [68]:
final.to_csv("210039_cat1by1null.csv",encoding='euc-kr',index=False)